### ISSUE TITLE
Status Code:405 Method Not Allowed

### ISSUE THREAD

**Issue by 1049759078** [huashengdun/webssh#10]
Request URL:http://118.25.33.81:8002/
Request Method:OPTIONS
Status Code:405 Method Not Allowed
Remote Address:118.25.33.81:8002
Referrer Policy:no-referrer-when-downgrade
Response Headers
view source
Access-Control-Allow-Headers:*
Access-Control-Allow-Methods:POST, GET, OPTIONS
Access-Control-Allow-Origin:*
Access-Control-Max-Age:1000
Content-Length:87
Content-Type:application/json
Date:Wed, 04 Apr 2018 06:38:00 GMT
Server:TornadoServer/5.0.1
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:zh-CN,zh;q=0.9
Access-Control-Request-Headers:x-csrftoken
Access-Control-Request-Method:POST
Connection:keep-alive
Host:118.25.33.81:8002
Origin:http://118.25.33.81:8001
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36

ajax请求总是405

**Comment by huashengdun** [comment]
Only GET, POST methods are supported.

**Comment by lytasky** [comment]
> Only GET, POST methods are supported.

is OPTIONS supported？
