### ISSUE TITLE
关于使用密钥登录。。。about privatekey????

### ISSUE THREAD

**Issue by bavol2000** [huashengdun/webssh#100]
使用密钥文本进行登录的时候出现这个，Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.
当使用密钥文本进行post登录的时候，那form表单的内容是需要填写什么才不会出现这种错误？

**Comment by huashengdun** [comment]
这个错误是现代浏览器的限制造成的。

**Comment by bavol2000** [comment]
我是使用chrome浏览器的，该 使用什么浏览器才不会出现这种错误？

**Comment by huashengdun** [comment]
据我所知，现代浏览器出于安全考虑是不允许通过`JavaScript`代码是设置file input的值。

**Comment by bavol2000** [comment]
那又需要如何才能使用privatekey来进行免密登录？？？看了例子都是使用帐号密码来进行登录，有没有什么办法可以使用密钥来进行免密登录？我尝试使用了privatekey这个参数进行Post传递，但是就是出现这样的错误提示，file input的值不能设置。
