### ISSUE TITLE
还是跨域的问题...

### ISSUE THREAD

**Issue by bavol2000** [huashengdun/webssh#102]
出现了跨域访问错误，Access to XMLHttpRequest at 'http://192.168.5.6:8888/' from origin 'http://192.168.5.6' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
参数已经设置了：--xsrf=False --address=192.168.5.6 --maxconn=100 --origin='*' --debug=True。
不知道是还有哪个地方没设置好？？

**Comment by bavol2000** [comment]
![image](https://user-images.githubusercontent.com/56681949/69245870-9d6e7e00-0be2-11ea-970d-e3cc0ff04d21.png)
通过console又能登录上去？？（已经把main.js里面的data._xsrf = _xsrf.value;注释掉了，不然会提示xsrf的值为空。）

**Comment by huashengdun** [comment]
如果使用Nginx了，Nginx配置贴出来看下？

**Comment by bavol2000** [comment]
> 如果使用Nginx了，Nginx配置贴出来看下？
    location / {        
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Credentials' 'false';
        add_header 'Access-Control-Allow-Methods' 'OPTION, POST, GET';    
        add_header 'Access-Control-Allow-Headers' 'X-Requested-With, Content-Type';
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_connect_timeout 75s;
        proxy_read_timeout 300s;   
        if (!-f $request_filename) {
            proxy_pass http://app_server_djangoapp;

            break;
        }
    }

**Comment by huashengdun** [comment]
通过页面正常的表单提交这些参数，跨域行吗？

**Comment by bavol2000** [comment]
> 通过页面正常的表单提交这些参数，跨域行吗？

通过页面正常的表单提交参数的话,如果设置了使用帐号和密码的话这种方式进行登录的话，可以。
但是我想使用privatekey来进行免密登录，如果使用privatekey的话，就不行，由于默认的privatekey的input是用file,我把它改成text，可是提交上去就出现跨域错误。。。。

**Comment by bavol2000** [comment]
非常感谢你的回答，，，，，对于privatekey使用免疫登录的话，privatekey这个input我把它设置成hidden居然可以了，，，，，，

**Comment by huashengdun** [comment]
问题解决了，那我就关闭了。
