### ISSUE TITLE
用frp穿透代理后无法登陆

### ISSUE THREAD

**Issue by mybove** [huashengdun/webssh#106]
用frp穿透代理后虽然可以打开登陆页面，但是点击登陆没有反应而无法登陆。

**Comment by huashengdun** [comment]
可以把问题描述得更加详细写吗？
还有，页面有没有什么提示， 浏览器console和服务端都有什么log？

**Comment by neosun100** [comment]
https://github.com/huashengdun/webssh/issues/111

原来是国人项目，赞！

**Comment by neosun100** [comment]
我也遇到了这个问题，debug信息在 https://github.com/huashengdun/webssh/issues/111

**Comment by zwc456baby** [comment]
frp 穿透代理的配置是什么？是使用的 http 穿透吗？这种 webssh 应该是使用了 websocket ，改成 tcp 穿透试下。
