### ISSUE TITLE
webssh 配合 lshell删除汉字会有问题

### ISSUE THREAD

**Issue by chenshun00** [huashengdun/webssh#107]
1、背景: 为了限制开发使用的命令和安全性而使用的lshell
2、重现步骤
 
  * 1、在机器(阿里云ECS)上安装 [lshell](https://github.com/ghantoos/lshell)
  * 2、机器上添加用户 `useradd chen` , `groupadd chen`
  * 3、`usermod -aG chen chen`
  * 4、`chsh -s /usr/bin/lshell chen`

3、然后通过webssh链接上去就会发现，删除汉字变成了删除一个字节，utf8下一个汉字3个字节，要删除3下才能删除掉1个汉字，界面就会错乱了

![image](https://user-images.githubusercontent.com/26037282/70675326-d40c5580-1cc3-11ea-899e-edaf6d6b579a.png)

然后我切换bash  `chsh -s /bin/bash chen` ，删除就没有问题，参看下图

![image](https://user-images.githubusercontent.com/26037282/70675411-159d0080-1cc4-11ea-9d03-c7e803e688cd.png)

**Comment by huashengdun** [comment]
bash没问题，那是不是lshell本身的问题？

**Comment by chenshun00** [comment]
我也想了这方面，然后我手动将 `chen` 切换到 `/bin/bash` .  参看下图，删除又没有问题，提奇怪的

![image](https://user-images.githubusercontent.com/26037282/70679981-b7771a00-1cd1-11ea-889d-0b934e8695a5.png)

**Comment by huashengdun** [comment]
你看下lshell是不是只支持`ascii`编码？

**Comment by chenshun00** [comment]
nice , 我没有想到这方面的问题，刚刚尝试了一下，现在已经解决了，ths :)
