### ISSUE TITLE
是新版本的问题吗？？？

### ISSUE THREAD

**Issue by bavol2000** [huashengdun/webssh#108]
这个是firefox控制台的出错信息。
源映射错误：request failed with status 404
源 URL：http://192.168.5.6:8888/static/css/bootstrap.min.css
源映射 URL：bootstrap.min.css.map

使用默认安装的，以前都没有.css.map........

**Comment by huashengdun** [comment]
你可以切换到旧版本，再打开firefox试下不就知道了。
