### ISSUE TITLE
需要在webssh外增加一层登陆账户密码

### ISSUE THREAD

**Issue by neosun100** [huashengdun/webssh#112]
![image](https://user-images.githubusercontent.com/13846998/71244684-0cf49c00-234e-11ea-8228-9e0e88994566.png)
能直接改main文件实现吗？
增加一组写死的user和passwd用于登陆

**Comment by neosun100** [comment]
```python
 43 def main():
 44     options.parse_command_line()
 45     loop = tornado.ioloop.IOLoop.current()
 46     app = make_app(make_handlers(loop, options), get_app_settings(options))
 47     ssl_ctx = get_ssl_context(options)
 48     server_settings = get_server_settings(options)
 49     app_listen(app, options.port, options.address, server_settings)
 50     if ssl_ctx:
 51         server_settings.update(ssl_options=ssl_ctx)
 52         app_listen(app, options.sslport, options.ssladdress, server_settings)
 53     loop.start()
 54 
 55 
 56 if __name__ == '__main__':
 57     main()
```

**Comment by huashengdun** [comment]
你参考下这个吧
https://www.tornadoweb.org/en/stable/guide/security.html#user-authentication

**Comment by neosun100** [comment]
发现有个亮点没用上，看到界面支持 time-based one-time password，这个等同于谷歌动态验证码吗？如何开启功能。这样比比套壳账号密码更安全

**Comment by huashengdun** [comment]
> 发现有个亮点没用上，看到界面支持 time-based one-time password，这个等同于谷歌动态验证码吗？如何开启功能。这样比比套壳账号密码更安全

是的，ssh服务器安装google authenticator。

**Comment by neosun100** [comment]
webssh里如何添加自己的2步验证

**Comment by neosun100** [comment]
我明白了，在服务器里添加2步验证，谢谢你！

**Comment by hello--world** [comment]
使用nginx测试了下，这样没问题：https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/
