### ISSUE TITLE
Option to to fix the ssh server adress?

### ISSUE THREAD

**Issue by dredkin** [huashengdun/webssh#113]
Hello!
I'm looking for a configuration option when I wouldn't need to enter the server address, but the address would be fixed.
I mean I don't like my server to be an ssh proxy for every scammer :)
E.g., it could be done like instead of a wssh html authorization form I'd see a prompt to enter the user name, like in the usual ssh client session:
```
login as:username
username@server's password: password
user@server:~$                                                                                                                                                                           

```
Can wssh be configured this way?

**Comment by huashengdun** [comment]
Hi, 
There is no this kind of configuration option.
Maybe you can try `RejectPolicy` with your `known_hosts`.
Only host (ssh server) in `known_hosts` is allowed.

**Comment by dredkin** [comment]
Oh, I can live with it!
Somehow I was thinking `known_hosts` restricts client addresses, not ssh hosts.

**Comment by dredkin** [comment]
Though I must note that the usual console way of login looks easier and more common for me.

**Comment by huashengdun** [comment]
> Oh, I can live with it!
> Somehow I was thinking `known_hosts` restricts client addresses, not ssh hosts.

`known_hosts` verifies the hostname and the key of  the ssh server to be connected.
