### ISSUE TITLE
Configuration for Totp

### ISSUE THREAD

**Issue by Tin-Bui** [huashengdun/webssh#118]
Thanks for the awesome app!
I am trying to setup the time-based one time password, but can't find any reference how to.
Could you please point to the right direction?
Thanks,
Tin.

**Comment by huashengdun** [comment]
Hi, 

Google "SSH Two Factor Authentication"

**Comment by Tin-Bui** [comment]
Right! it just dawned on me that webssh doesn't do the otp by itself, but just passing it on.
Since It'll take me a while to come back and I am pretty sure I am on the right track.
I'll close this issue for now.
Thanks!
