### ISSUE TITLE
Url Command breaks when contains '=' symbol

### ISSUE THREAD

**Issue by KiranTarafderGitHub** [huashengdun/webssh#119]
i am loading the following url through jquery 

http://172.16.14.13:8888/?hostname=172.16.14.13&username=root&password=xyz&command=sshpass -p  'xyz' ssh -t root@172.16.14.14 sshpass -p 'abc' ssh -o ssh StrictHostKeyChecking=no root@172.16.14.15 -p 2223

it returns the following response:
Last login: Tue Jan 14 11:48:13 2020 from 172.16.14.13
[root@localhost ~]$ sshpass -p  'xyz' ssh -t root@172.16.14.14 sshpass -p 'abc' ssh -o ssh StrictHostKeyChecking
command-line: line 0: Bad configuration option: ssh
Connection to 172.16.14.14 closed.

Apparently the command passed through url is breaking at '=' symbol. When i removed 'StrictHostKeyChecking=no' from the command it works properly.

**Comment by huashengdun** [comment]
Fixed https://github.com/huashengdun/webssh/commit/359a91b5e801aae840e78e79454fee045f68b57f

**Comment by KiranTarafderGitHub** [comment]
Thank you for fixing the issue.. Closing the issue now.
