### ISSUE TITLE
Is it possible to use a custom font with the internal webserver?

### ISSUE THREAD

**Issue by pandel** [huashengdun/webssh#120]
Hi!

First, I really love this tool! It is absolutely amazing and I use it constantly. Thanks for your hard work!

I have just one question:

Recently I introduced powerline based styling to vim  and tmux, but sadly the special characters of the powerline font are not delivered correctly in the terminal window. Terminal type is xterm-256color and browser encoding is UTF-8, so I think I need to specify a custom font, but I don't know how to do it while using the interal web server.

As I have no clue of JS and such, how am I going to achieve that?

Regards,
Holger

**Comment by pandel** [comment]
Sometimes one has to think a bit longer.... Found a solution - modified index.html in templates folder / created fonts folder and inserted font file. Done.

Would be nice, if that could be a little bit easier to configure, but I can live with what I have got.

**Comment by huashengdun** [comment]
Hi,

Just updated the code to make it easier to use custom font.
https://github.com/huashengdun/webssh#custom-font
