### ISSUE TITLE
private key url support ?

### ISSUE THREAD

**Issue by stribehou** [huashengdun/webssh#123]
Hello, 

Can we hope for the private key to be supported as an URL variable ? 

That's blocking me from using webssh, which would be perfect for my needs otherwise.
Maybe restrict to ed25519 if length is a problem, even with no password ? 

Thank you.

**Comment by huashengdun** [comment]
Hi,

I don't think it is a good idea .
Even for password URL variable encrypted with base64 is still compromising.

**Comment by bicchi** [comment]
Would it be possible to star wssh with a default private key as a command line parameter? This way one doesn’t have to enter one in the form. 

Use the value to populate the form when called. This would be a feature I could use right now.
