### ISSUE TITLE
Program stopped even passed password Authentication

### ISSUE THREAD

**Issue by ycpjy1989** [huashengdun/webssh#125]
Once I start the program, it will stop even I passed the password Authentication. 
I can see the log:
[I 200212 22:51:30 handler:442] Connecting to 192.168.104.98:22
[I 200212 22:51:31 transport:1819] Connected (version 2.0, client OpenSSH_7.4)
/usr/local/lib/python2.7/dist-packages/paramiko/client.py:837: UserWarning: Unknown ssh-rsa host key for 192.168.104.98: 8068d198d8057d3e1b4b45470dcc4ba7
  key.get_name(), hostname, hexlify(key.get_fingerprint())
[I 200212 22:51:31 handler:87] Trying password authentication
[I 200212 22:51:32 transport:1819] Authentication (password) successful!

**Comment by ycpjy1989** [comment]
And it is not a Linux device and it works well if linux.

**Comment by ycpjy1989** [comment]
[I 200213 15:37:14 settings:98] AutoAddPolicy
[I 200213 15:37:14 main:39] Listening on :8888 (http)
[D 200213 15:37:18 handler:225] netloc: 192.168.104.169:8888
[D 200213 15:37:18 handler:228] host: 192.168.104.169:8888
[D 200213 15:37:18 handler:410] (u'192.168.104.98', 22, u'admin', u'a10', None)
[I 200213 15:37:18 handler:443] Connecting to 192.168.104.98:22
[D 200213 15:37:18 transport:1819] starting thread (client mode): 0xe92bce10L
[D 200213 15:37:18 transport:1819] Local version/idstring: SSH-2.0-paramiko_2.7.1
[D 200213 15:37:18 transport:1819] Remote version/idstring: SSH-2.0-OpenSSH_7.4
[I 200213 15:37:18 transport:1819] Connected (version 2.0, client OpenSSH_7.4)
[D 200213 15:37:18 transport:1819] kex algos:[u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group14-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr'] client mac:[u'hmac-sha1', u'hmac-sha2-512', u'hmac-sha2-256'] server mac:[u'hmac-sha1', u'hmac-sha2-512', u'hmac-sha2-256'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
[D 200213 15:37:18 transport:1819] Kex agreed: diffie-hellman-group-exchange-sha256
[D 200213 15:37:18 transport:1819] HostKey agreed: ssh-rsa
[D 200213 15:37:18 transport:1819] Cipher agreed: aes128-ctr
[D 200213 15:37:18 transport:1819] MAC agreed: hmac-sha2-256
[D 200213 15:37:18 transport:1819] Compression agreed: none
[D 200213 15:37:18 transport:1819] Got server p (2048 bits)
[D 200213 15:37:18 transport:1819] kex engine KexGexSHA256 specified hash_algo <built-in function openssl_sha256>
[D 200213 15:37:18 transport:1819] Switch to new keys ...
[I 200213 15:37:18 handler:87] update
[I 200213 15:37:18 handler:88] Trying password authentication
[D 200213 15:37:18 transport:1819] userauth is OK
[I 200213 15:37:18 transport:1819] Authentication (password) successful!
[D 200213 15:37:18 channel:1212] [chan 0] Max packet in: 32768 bytes
[D 200213 15:37:18 transport:1819] Received global request "hostkeys-00@openssh.com"
[D 200213 15:37:18 transport:1819] Rejecting "hostkeys-00@openssh.com" global request from server.
[D 200213 15:37:18 channel:1212] [chan 0] Max packet out: 32768 bytes
[D 200213 15:37:18 transport:1819] Secsh channel 0 opened.
[D 200213 15:37:18 channel:1212] [chan 0] Sesch channel 0 request ok
[D 200213 15:37:18 channel:1212] [chan 0] Sesch channel 0 request ok
[D 200213 15:37:18 channel:1212] [chan 1] Max packet in: 32768 bytes
[D 200213 15:37:18 channel:1212] [chan 1] Max packet out: 32768 bytes
[D 200213 15:37:18 transport:1819] Secsh channel 1 opened.
[D 200213 15:37:18 channel:1212] [chan 1] Sesch channel 1 request ok
[D 200213 15:37:18 channel:1212] [chan 1] Sesch channel 1 request ok
[D 200213 15:37:18 channel:1212] [chan 1] EOF sent (1)
[D 200213 15:37:18 handler:432] '$SHELL -ilc "locale charmap"' => "unlink: cannot unlink '/tmp/.rimacli_lock': No such file or directory\r\n"
[D 200213 15:37:18 channel:1212] [chan 1] EOF received (1)
[D 200213 15:37:18 channel:1212] [chan 2] Max packet in: 32768 bytes
[D 200213 15:37:18 channel:1212] [chan 2] Max packet out: 32768 bytes
[D 200213 15:37:18 transport:1819] Secsh channel 2 opened.
[D 200213 15:37:18 channel:1212] [chan 2] Sesch channel 2 request ok
[D 200213 15:37:18 channel:1212] [chan 2] Sesch channel 2 request ok
[D 200213 15:37:18 channel:1212] [chan 2] EOF sent (2)

**Comment by huashengdun** [comment]
Try starting the server with the option `encoding` like,
```bash
wssh --encoding='utf-8'
```

**Comment by ycpjy1989** [comment]
I changed the code with "utf-8", I think it is same as the option. 
Thanks
