### ISSUE TITLE
这名字是“华盛顿”吗。。。另外，用django的话，有戏没？

### ISSUE THREAD

**Issue by hgmmym** [huashengdun/webssh#128]
看到huashengdun的时候，我猜是国人。看了readme，这英语这么6，我推翻了国人的猜测。进了Issues，是国人没跑了。。。找了一大堆webssh，这个非常666.

因为一直用的django裸跑网页，为了图轻快，没用nginx一类。这个webssh可否能在django上面跑？如果大神不用django，就忘了我问的吧。。。。

对了，这个时间点，祝大神身体健康别发烧。。。

**Comment by huashengdun** [comment]
我是国人。

django 只是一个web framework, 自带的那个服务器是用来开发调试的，所以是不适合裸跑网页， 需要一个web server配合。

我很好，谢谢你的祝福，也祝你健康。
