### ISSUE TITLE
Is Safari on macOS supported?

### ISSUE THREAD

**Issue by paulgit** [huashengdun/webssh#129]
I have successfully installed webssh behind NGINX and can use it without issue with Firefox, but if I use Safari 13.0.5 on my Mac I do not see the terminal, though the log shows a successful connection:

```
[I 200216 22:13:14 handler:161] Parsing private key 'id_ed25519'
[I 200216 22:13:14 handler:443] Connecting to xxxxxxxx
[I 200216 22:13:15 transport:1819] Connected (version 2.0, client OpenSSH_7.6p1)
[I 200216 22:13:15 handler:71] Trying publickey authentication
[I 200216 22:13:16 transport:1819] Authentication (publickey) successful!
[I 200216 22:13:17 web:2246] 200 POST / (xxxxxxxx) 3055.75ms
[W 200216 22:13:20 worker:28] Recycling worker 140343312382384
[I 200216 22:13:20 worker:115] Closing worker 140343312382384 with reason: worker recycled
[I 200216 22:13:20 worker:122] Connection to xxxxxxxx lost
```

Is Safari supported?

**Comment by huashengdun** [comment]
See here https://github.com/huashengdun/webssh/issues/25, tested with Safari 11.x, but may have problems with future higher version. 
Do you have any clue why it was failing when using Safari 13.0.5?

**Comment by huashengdun** [comment]
I've just tested with Safari 13.0.1 and it works.

**Comment by huashengdun** [comment]
Just tested with Safari 13.0.5 and it also worked.
![safari](https://user-images.githubusercontent.com/909962/75091052-2d3a1480-55a4-11ea-88c8-698ac4976acf.png)

**Comment by paulgit** [comment]
Strange, I cannot get it to work at all. Is your WebSSH server behind NGINX also?

**Comment by huashengdun** [comment]
> [I 200216 22:13:17 web:2246] 200 POST / (xxxxxxxx) 3055.75ms

Seems your problem is caused by the delay of network.
Try increasing the value of the variable `DELAY`  which is in the file handler.py

**Comment by paulgit** [comment]
> > [I 200216 22:13:17 web:2246] 200 POST / (xxxxxxxx) 3055.75ms
> 
> Seems your problem is caused by the delay of network.
> Try increasing the value of the variable `DELAY` which is defined in the file handler.py.

This didn’t appear to work for me, as it’s specific to Safari on my computer I can only assume there is nothing wrong serverside (Chrone and Firefox work fine). This weekend I should get access to another Mac so I can try Safari again.

**Comment by huashengdun** [comment]
If you just want to test if Safari is supported, I suggest you to simplify the deployment of this app.
Don't use nginx, install webssh on your local computer and connect to your local ssh server.
