### ISSUE TITLE
 tail -f /var/log/lastlog连接中断

### ISSUE THREAD

**Issue by d-anz** [huashengdun/webssh#13]
如题，有些正常的日志tail也会立即中断，请问如何解决？

**Comment by huashengdun** [comment]
有什么错误提示没？

**Comment by d-anz** [comment]
执行tail -f /var/log/lastlog有如下报错。

[I 180511 23:35:27 worker:98] Closing worker 140550869492792 with reason Invalid UTF-8 in text frame

**Comment by huashengdun** [comment]
这个是因为你的/var/log/lastlog包含了非UTF-8的字符，浏览器websocket 无法解码接收到字节流， 从而断开了与服务器websocket的连接。

**Comment by huashengdun** [comment]
这个问题已经解决，浏览器遇到非UTF-8的字符不再断开websocket。

**Comment by anythingwhat** [comment]
请教下遇到非UTF-8的字符不再断开websocket的问题是怎么解决的，代码是什么地方

**Comment by huashengdun** [comment]
https://github.com/huashengdun/webssh/commit/191bb109e07e13eeae65c85f5a22c4f9bc8b0e7e

**Comment by huashengdun** [comment]
@anythingwhat 
邮箱已回复。

**Comment by anythingwhat** [comment]
@huashengdun ，是guangdianabc这个126邮箱吗，没有收到

**Comment by anythingwhat** [comment]
刚收到了
