### ISSUE TITLE
Add option to change SSH connection timeout

### ISSUE THREAD

**Issue by Chunters** [huashengdun/webssh#130]
Some devices require more than 6 seconds to connect to them.
SSH connect have hardcoded 6 second timeout to connect in handler.py.
Can you add option to change timeout or some workaround without change code in actual version?

https://github.com/huashengdun/webssh/blob/7110def7475776b4435880f4c9a754fa4af1d6f3/webssh/handler.py#L446

**Comment by huashengdun** [comment]
Added timeout option.

**Comment by Chunters** [comment]
Thanks a lot!
