### ISSUE TITLE
wssh.send issues with special characters

### ISSUE THREAD

**Issue by whattheserver** [huashengdun/webssh#132]
First off Want to say great work on this terminal it is amazing.

The issue I'm having is due to the special characters not being escaped and no real way to send it a multiline raw string with special characters. or pass the wssh.send function a variable from Python or  

This obviously works nicely.
`wssh.send('ls -l');`

But when say doing something like the below bash oneliner it looks like the only option is to manually escape.  the ' " special characters manually which is time-consuming and error-prone.

```
wssh.send('for phpver in $(ls -1 /opt/cpanel/ |grep ea-php | sed \'s/ea-php//g\') ; do echo "PHP $phpver" ; /opt/cpanel/ea-php$phpver/root/usr/bin/php -i |grep -Ei \'memory_limit|post_max_size|upload_max_filesize|max_execution_time\' && echo "" ; done');
undefined
```

I also tried to send the string as a variable was not able to get that to work.

Is there some way we can add support for escaping or raw strings support?

PHP has a library for doing this for its special characters.
https://www.php.net/manual/en/function.htmlspecialchars.php

`echo htmlspecialchars($cPanelPHPVersions, ENT_QUOTES, 'UTF-8');`

```
$cPanelPHPVersions = <<<EOT
'for phpver in $(ls -1 /opt/cpanel/ |grep ea-php | sed \'s/ea-php//g\') ; do echo "PHP $phpver" ; /opt/cpanel/ea-php$phpver/root/usr/bin/php -i |grep -Ei \'memory_limit|post_max_size|upload_max_filesize|max_execution_time\' && echo "" ; done
```

I also see Python has raw strings and also ''' that can be used to do comments and multiline strings.
`'''`
https://stackoverflow.com/questions/9589301/python-here-document-without-newlines-at-top-and-bottom

Is there a way that's recommended to pass these complex oneliners to the current session either via native python or passing a python variable to this which has special characters that it will accept?

I'm trying to allow rapid oneliners like the above to be buttons on a widget so a user can click the button from a list and its input into the terminal preformatted.
Just an image for visualizion
![image](https://user-images.githubusercontent.com/1596188/75068926-21742280-54be-11ea-9946-09e95d7f54fc.png)

Using pysides QWebEngine to show the terminal. If that helps.

**Comment by huashengdun** [comment]
Base on my experience, the only special character for wssh.send is "\\".
Did you test your oneliner in the terminal?

**Comment by whattheserver** [comment]
Command entered normally via browser copy and paste.
Command:
`for phpver in $(ls -1 /opt/cpanel/ |grep ea-php | sed 's/ea-php//g') ; do echo "PHP $phpver" ; /opt/cpanel/ea-php$phpver/root/usr/bin/php -i |grep -Ei 'memory_limit|post_max_size|upload_max_filesize|max_execution_time' && echo "" ; done`

![image](https://user-images.githubusercontent.com/1596188/75115335-649fd400-562b-11ea-8191-aac2148b9899.png)

Command entered normally without escaping via browser console.
`wssh.send('for phpver in $(ls -1 /opt/cpanel/ |grep ea-php | sed 's/ea-php//g') ; do echo "PHP $phpver" ; /opt/cpanel/ea-php$phpver/root/usr/bin/php -i |grep -Ei 'memory_limit|post_max_size|upload_max_filesize|max_execution_time' && echo "" ; done');`

![image](https://user-images.githubusercontent.com/1596188/75115353-987af980-562b-11ea-80fe-596dc7664ccd.png)

Command entered via browser console with the inner ' escaped manually:
`wssh.send('for phpver in $(ls -1 /opt/cpanel/ |grep ea-php | sed \'s/ea-php//g\') ; do echo "PHP $phpver" ; /opt/cpanel/ea-php$phpver/root/usr/bin/php -i |grep -Ei \'memory_limit|post_max_size|upload_max_filesize|max_execution_time\' && echo "" ; done');`

![image](https://user-images.githubusercontent.com/1596188/75115363-b5173180-562b-11ea-8c83-7a84997444cd.png)

I know the commands are good. I use them daily via copy and past and have an index of these that are all pretested.

Manually escaping them all to send over the console while possible is not exactly ideal.

Suggestion: Can we make the delimiter be like the Python docstring comments? This would make it so no escaping is needed and anything between the set of """ would be passed exactly how it is.

wssh.send("""completxcommandstringhere""");


Example:
wssh.send("""ls -l""");

Example2:
wssh.send("""for phpver in $(ls -1 /opt/cpanel/ |grep ea-php | sed 's/ea-php//g') ; do echo "PHP $phpver" ; /opt/cpanel/ea-php$phpver/root/usr/bin/php -i |grep -Ei 'memory_limit|post_max_size|upload_max_filesize|max_execution_time' && echo "" ; done""");

**Comment by huashengdun** [comment]
Use double quotes nested when the whole string is quoted by single quote, vice versa.
