### ISSUE TITLE
运行建议

### ISSUE THREAD

**Issue by fcwys** [huashengdun/webssh#138]
若有可能，希望能封装为一个单文件+一个配置文件的结构，支持多平台，会更方便

**Comment by huashengdun** [comment]
如果pypi能接受你的意见就好了。

**Comment by fcwys** [comment]
打扰了😂

**Comment by huashengdun** [comment]
> 打扰了joy

 Windows下有py2exe软件，不知道 Linux/Unix, Mac下有没有类似的软件。

**Comment by huashengdun** [comment]
刚去搜索了下，发现PyInstaller。
