### ISSUE TITLE
Can you set the server to not store data to localstorage or customize the contents of the stored data

### ISSUE THREAD

**Issue by jahnli** [huashengdun/webssh#139]
Can you set the server to not store data to localstorage or customize the contents of the stored data

Each time the server seems to be actively storing to localstorage，But I want to customize or not store

![image](https://user-images.githubusercontent.com/20943608/76936722-5d1fd200-692e-11ea-89b2-345300260f29.png)

**Comment by huashengdun** [comment]
Comment this line `store_items(fields, result.data);` in file main.js if you really want to disable storing data into localstorage.

**Comment by jahnli** [comment]
Ok, thank you very much


| |
JahnLi
|
|
jahnli@163.com
|
签名由网易邮箱大师定制
On 3/22/2020 18:25，Shengdun Hua<notifications@github.com> wrote：

Comment this line store_items(fields, result.data); in file main.js if you really want to disable storing data into localstorage.
