### ISSUE TITLE
主机名很长的情况下，命令稍微长不会换行

### ISSUE THREAD

**Issue by d-anz** [huashengdun/webssh#14]
例如：
111111111111111111app-xx-5876fd8bcf-xnwhk dddd]$ 11111111111111111111111111111

前面的1111111把主机名覆盖了，本来应该是这样的
[user@tes-bbbbb-app-xx-5876fd8bcf-xnwhk dddd]$ 11111111111111111111111111111
111111111111111111

**Comment by huashengdun** [comment]
这个可能是前端排版的问题，你可以把页面拉大一点。
或者你也可以改变下你命令行的提示符， 比如把主机名缩短点。

**Comment by huashengdun** [comment]
这个貌似是ssh shell的问题，看下面这个
https://github.com/xtermjs/xterm.js/issues/179
