### ISSUE TITLE
解决cloudflare代理后websocket连接认证失败的问题

### ISSUE THREAD

**Issue by 1-1-2** [huashengdun/webssh#141]
## Websocket authentication failed.

原因在于cloudflare的https访问和wss访问是由两个不同的代理IP发出的（P.S.添加real ip header不在cf免费计划中，只能另寻他路），而目前版本下依据IP进行worker的索引，也即[IP与ID绑定](https://github.com/huashengdun/webssh/issues/87#issuecomment-532022860)，导致wss握手的IP下没有对应的worker，握手失败。

当前版本下wss请求时会发送对应的worker_id，而且默认的worker_recycle延时为3秒，加上_xsrf和https通讯，且ID使用一次后失效，不进行IP认证从安全性上应该可行。

### 解决方案

> 本人为debian系统，python2.7。

思路：直接从clients中遍历id获得worker
修改`/usr/local/lib/python2.7/dist-packages/webssh/handler.py`中`WsockHandler.open`函数如下：
```python
    def open(self):
        self.src_addr = self.get_client_addr()
        logging.info('Connected from {}:{}'.format(*self.src_addr))

        ip = self.src_addr[0]

        try:
            worker_id = self.get_value('id')
        except (tornado.web.MissingArgumentError, InvalidValueError) as exc:
            self.close(reason=str(exc))
        else:
            for workers in clients.values():
                worker = workers.get(worker_id)
                if worker:
                    break
            if worker:
                workers[worker_id] = None
                self.set_nodelay(True)
                worker.set_handler(self)
                self.worker_ref = weakref.ref(worker)
                self.loop.add_handler(worker.fd, worker, IOLoop.READ)
            else:
                self.close(reason='Websocket authentication failed.')
```

欢迎交流指正~

**Comment by huashengdun** [comment]
https://github.com/huashengdun/webssh/issues/71

**Comment by huashengdun** [comment]
另外cloudflare提供了一个header `CF-Connecting-IP`可以利用，详见https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-

**Comment by 1-1-2** [comment]
尝试了[这里](https://github.com/huashengdun/webssh/issues/71#issuecomment-506721600)的操作之后的确有效，之前没能领悟内容的意思，这里按照我的理解稍作补充：

解决方法：

1. webssh作为独立服务（需占用80/443端口）并启用xheaders功能（默认启用）。
`wssh --port=80 --sslport=443 --certfile='cert.crt' --keyfile='cert.key'`
Cloudflare支持X-Forwarded-For header并能被webssh读取，访问形式如下：
  ```
  client <---> cloudflare <---> wssh
  ```

2. webssh作为本地服务运行，禁用xheaders功能，并使用nginx/Caddy等作为前置代理。
`wssh --address='127.0.0.1' --xheaders=False`
访问形式如下：
  ```
  client <---> cloudflare <---> nginx/Caddy <---> wssh
  ```

另附Caddy配置

```
domain.com {
    tls {
        dns cloudflare
    }
    proxy / 127.0.0.1:8888 {
        websocket
        transparent
    }
}
```

感谢~

**Comment by 1-1-2** [comment]
另外提出项目[README中deployment](https://github.com/huashengdun/webssh/blob/master/README.md#deployment)部分两个运行命令的xheaders参数是不是写反了。

**Comment by huashengdun** [comment]
> 另外提出项目[README中deployment](https://github.com/huashengdun/webssh/blob/master/README.md#deployment)部分两个运行命令的xheaders参数是不是写反了。

那两个命令只是演示而已，并不针对cloudflare.
