### ISSUE TITLE
 bad host key 

### ISSUE THREAD

**Issue by chenshun00** [huashengdun/webssh#147]
界面使用key登陆提示bad host key  , 命令行是可以登陆的，界面使用密码也能登陆

**Comment by huashengdun** [comment]
如果你的webssh有使用自定义的 known_hosts，那你得更新它， 然后重启webssh。
如果没有使用 known_hosts，直接重启webssh即可。

**Comment by chenshun00** [comment]
嗯，我没有重启进程，现在重启了进程而已了。 感谢 @huashengdun

**Comment by wanghang7894** [comment]
有没有办法自动清理host_key
