### ISSUE TITLE
提几个问题-重度用户

### ISSUE THREAD

**Issue by d-anz** [huashengdun/webssh#15]
1. 窗口支持自动伸缩，虽然js里面有自动伸缩，但是每次都取不到term的宽、高。导致每次都需要手动拉动窗口才会生效。猜测问题所在，js加载完毕，但是css可能还没下完，导致没取到。
2. vim等还是小窗口问题，虽然整个网页能伸缩，但是chan内部还是col 80，line 24，所以top、ps、vim其实都是小窗口。建议窗口变动之后，能动态调用self.chan.resize_pty....
3. 编码问题，这个问题真的很明显，tail -f 日志，一个很正常的日志文件，经常性的断开。经过改编码之后，目前稳定了。

最后说下，这个项目非常棒，目前已经用在生产环境。期待更多功能。

**Comment by huashengdun** [comment]
感谢使用并反馈。

1. 刚开始创建term时是采用默认高度和宽度的，不同的浏览器也是有差异的。
    我不知道你是怎么取term的宽、高的？
2. 这个等有时间研究下你的建议。
3. 编码问题，还是用统一的utf-8为好，这是websocket传递文字的默认编码。
    如果没有统一的编码，那么需要服务器那边还得检测编码，这个有点浪费资源且耗时。

**Comment by d-anz** [comment]
1. 刚开始创建term时是采用默认高度和宽度的，不同的浏览器也是有差异的。
我不知道你是怎么取term的宽、高的？
------ 用你提供的方法
是否可以留下一个联系方式

**Comment by huashengdun** [comment]
第三个编码问题已经解决，浏览器遇到非UTF-8的字符不再断开websocket了。
但是默认的编码还是utf-8，所以浏览器那边非utf-8字符会显示乱码。

关于联系方式， 你可以把这个库fork下来，使用git log查看。

**Comment by huashengdun** [comment]
根据你的建议，我更新了代码。
你可以测试下代码看你提到的1，2两个问题有没有很好的解决。
欢迎提更多意见和反馈，谢谢。

**Comment by huashengdun** [comment]
非utf-8的编码也支持了.
