### ISSUE TITLE
Deployed wssh on production having HAproxy set up - but wssh is not working

### ISSUE THREAD

**Issue by vishalorange** [huashengdun/webssh#150]
NODE A - HA Proxy 
NODE B - wssh setup

apache configuration on NODE B is

> RewriteEngine on
> ProxyPass /shell http://127.0.0.1:8888
> ProxyPassReverse /shell/ http://127.0.0.1:8888
> RewriteCond %{HTTP:Upgrade} ^WebSocket$ [NC,OR]
> RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC,OR]

**When hitting URL having node B ip**

> https://code-bypassproxy.casa.uro.equant.com/shell/?hostname=10.71.130.46&username=guest&password=Z3Vlc3QK

> Connection` to 10.71.130.46:22 is not allowed

**When hitting URL having node A ip**

> https://code-bypassproxy.casa.uro.equant.com/shell/?hostname=10.71.130.159&username=guest&password=Z3Vlc3QK

Then below is log of wssh

> [I 200414 11:13:12 web:2250] 200 GET /?encoding=utf-8&hostname=10.71.130.159&username=guest&password=Z3Vlc3QK (127.0.0.1) 1.05ms
> [I 200414 11:13:12 web:2250] 304 GET /static/css/bootstrap.min.css (127.0.0.1) 1.40ms
> [I 200414 11:13:12 web:2250] 304 GET /static/css/xterm.min.css (127.0.0.1) 0.74ms
> [I 200414 11:13:12 web:2250] 304 GET /static/css/fullscreen.min.css (127.0.0.1) 0.70ms
> [I 200414 11:13:12 web:2250] 304 GET /static/js/jquery.min.js (127.0.0.1) 0.65ms
> [I 200414 11:13:12 web:2250] 304 GET /static/js/popper.min.js (127.0.0.1) 1.03ms
> [I 200414 11:13:12 web:2250] 304 GET /static/js/bootstrap.min.js (127.0.0.1) 0.98ms
> [I 200414 11:13:12 web:2250] 304 GET /static/js/xterm.min.js (127.0.0.1) 0.87ms
> [I 200414 11:13:13 web:2250] 304 GET /static/js/xterm-addon-fit.min.js (127.0.0.1) 1.06ms
> [I 200414 11:13:13 web:2250] 304 GET /static/js/main.js (127.0.0.1) 0.72ms
> [D 200414 11:13:13 handler:410] ('10.71.130.159', 22, 'guest', 'guest', None)
> [I 200414 11:13:13 handler:447] Connecting to 10.71.130.159:22
> [D 200414 11:13:13 transport:1819] starting thread (client mode): 0xd423da90
> [D 200414 11:13:13 transport:1819] Local version/idstring: SSH-2.0-paramiko_2.7.1
> [D 200414 11:13:13 transport:1819] Remote version/idstring: SSH-2.0-OpenSSH_7.4
> [I 200414 11:13:13 transport:1819] Connected (version 2.0, client OpenSSH_7.4)
> [D 200414 11:13:13 transport:1819] kex algos:['curve25519-sha256', 'curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group16-sha512', 'diffie-hellman-group18-sha512', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha256', 'diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1'] server key:['ssh-rsa', 'rsa-sha2-512', 'rsa-sha2-256', 'ecdsa-sha2-nistp256', 'ssh-ed25519'] client encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com', 'aes128-cbc', 'aes192-cbc', 'aes256-cbc', 'blowfish-cbc', 'cast128-cbc', '3des-cbc'] server encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com', 'aes128-cbc', 'aes192-cbc', 'aes256-cbc', 'blowfish-cbc', 'cast128-cbc', '3des-cbc'] client mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] server mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
> [D 200414 11:13:13 transport:1819] Kex agreed: curve25519-sha256@libssh.org
> [D 200414 11:13:13 transport:1819] HostKey agreed: ecdsa-sha2-nistp256
> [D 200414 11:13:13 transport:1819] Cipher agreed: aes128-ctr
> [D 200414 11:13:13 transport:1819] MAC agreed: hmac-sha2-256
> [D 200414 11:13:13 transport:1819] Compression agreed: none
> [D 200414 11:13:13 transport:1819] kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
> [D 200414 11:13:13 transport:1819] Switch to new keys ...
> [I 200414 11:13:13 handler:87] Trying password authentication
> [D 200414 11:13:13 transport:1819] userauth is OK
> [I 200414 11:13:13 transport:1819] Authentication (password) successful!
> [D 200414 11:13:13 channel:1212] [chan 0] Max packet in: 32768 bytes
> [D 200414 11:13:13 transport:1819] Received global request "hostkeys-00@openssh.com"
> [D 200414 11:13:13 transport:1819] Rejecting "hostkeys-00@openssh.com" global request from server.
> [D 200414 11:13:13 channel:1212] [chan 0] Max packet out: 32768 bytes
> [D 200414 11:13:13 transport:1819] Secsh channel 0 opened.
> [D 200414 11:13:13 channel:1212] [chan 0] Sesch channel 0 request ok
> [D 200414 11:13:13 channel:1212] [chan 0] Sesch channel 0 request ok
> [D 200414 11:13:13 channel:1212] [chan 1] Max packet in: 32768 bytes
> [D 200414 11:13:13 channel:1212] [chan 1] Max packet out: 32768 bytes
> [D 200414 11:13:13 transport:1819] Secsh channel 1 opened.
> [D 200414 11:13:13 channel:1212] [chan 1] Sesch channel 1 request ok
> [D 200414 11:13:13 channel:1212] [chan 1] Sesch channel 1 request ok
> [D 200414 11:13:13 channel:1212] [chan 1] EOF sent (1)
> [D 200414 11:13:13 channel:1212] [chan 1] EOF received (1)
> [D 200414 11:13:13 handler:436] '$SHELL -ilc "locale charmap"' => b"rbash: /bin/bash: restricted: cannot specify `/' in command names\r\n"
> [D 200414 11:13:13 channel:1212] [chan 2] Max packet in: 32768 bytes
> [D 200414 11:13:13 channel:1212] [chan 2] Max packet out: 32768 bytes
> [D 200414 11:13:13 transport:1819] Secsh channel 2 opened.
> [D 200414 11:13:13 channel:1212] [chan 2] Sesch channel 2 request ok
> [D 200414 11:13:13 channel:1212] [chan 2] Sesch channel 2 request ok
> [D 200414 11:13:13 channel:1212] [chan 2] EOF sent (2)
> [D 200414 11:13:13 channel:1212] [chan 2] EOF received (2)
> [D 200414 11:13:13 handler:436] '$SHELL -ic "locale charmap"' => b"rbash: /bin/bash: restricted: cannot specify `/' in command names\r\n"
> [W 200414 11:13:13 handler:441] Could not detect the default ecnoding.
> [I 200414 11:13:13 web:2250] 200 POST /?encoding=utf-8&hostname=10.71.130.159&username=guest&password=Z3Vlc3QK (127.0.0.1) 212.42ms
> [W 200414 11:13:13 web:2250] 400 GET /ws?id=139942203022528 (127.0.0.1) 0.54ms
> [D 200414 11:13:13 websocket:240] Can "Upgrade" only to "WebSocket".
> [W 200414 11:13:16 worker:28] Recycling worker 139942203022528
> [I 200414 11:13:16 worker:115] Closing worker 139942203022528 with reason: worker recycled
> [D 200414 11:13:16 channel:1212] [chan 0] EOF sent (0)
> [I 200414 11:13:16 worker:122] Connection to 10.71.130.159:22 lost
> [D 200414 11:13:16 worker:125] {}
> [D 200414 11:13:16 transport:1819] EOF in transport thread 

In Firefox browser console

> Firefox can’t establish a connection to the server at wss://code-bypassproxy.casa.uro.equant.com/shell/ws?id=139942183556656

**Comment by huashengdun** [comment]
```[W 200414 11:13:13 web:2250] 400 GET /ws?id=139942203022528 (127.0.0.1) 0.54ms```
The status code is 400 which means the client (your browser) sends a bad request.
Probably your configuration of proxying Websocket is not correct.

**Comment by huashengdun** [comment]
```Connection` to 10.71.130.46:22 is not allowed```
This means you are using `Reject` policy and the hostname of the destined ssh server is not in your known_hosts.

**Comment by ivishalvarshney** [comment]
Yes this is important to have both apache and webssh configuration combination to make things working.
In my case below is the configuration (if it helps someone)
**apache**

> `<Location /shell>`
   ProxyPreserveHost On
   ProxyPass  http://127.0.0.1:8888
   ProxyPassReverse  http://127.0.0.1:8888
   RewriteEngine On
   RewriteCond %{HTTP:Upgrade} ^WebSocket$ [NC,OR]
   RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC,OR]
   RewriteRule /ws*  ws://localhost:8888/ws$1 [P,L]
`</Location>`

And Web ssh command
`wssh --certfile='/root/vishal/certs/AUTH-CERT_pem.cer' --keyfile='/root/vishal/certs/private.key' --logging=debug   --sslport=4433 --origin=https://something.com  --address=127.0.0.1 --log-file-prefix=/var/log/project/wssh.log`
