### ISSUE TITLE
invalid hostname

### ISSUE THREAD

**Issue by lb20150514** [huashengdun/webssh#156]
why remote connection to part of machines is reported to have invalid hostname like:diag-pv_navi21_001 while it works well by ssh? does the underline matter？

**Comment by huashengdun** [comment]
Yes, the underscore is not a legal character for use in hostnames.

**Comment by lb20150514** [comment]
but if i directly return true for the is_valid_hostname function and restart wssh ,it still report the error. do i need to update other configures?

**Comment by huashengdun** [comment]
This is because hostname is validated on both sides,  front end and back end.
