### ISSUE TITLE
Login hangs if the session directly enters a command like tmux

### ISSUE THREAD

**Issue by toolleeo** [huashengdun/webssh#160]
I'm trying to enter directly into a tmux session once logged in using webssh.
However, webssh does not login and seems to hang during the login.

To replicate the issue, just have a ssh-reachable user with a normal bash login shell and a tmux command at the end of the .bashrc file.
Trying to login from webssh for that user hangs the login process.

If tmux is launched manually after login, it works fine.

Actually, I'm not sure whether this is an issue of webssh, xterm.js or the ssh library used for the login.

Any clue?

BTW, the same issue happens when trying to directly enter a schroot session through the ForceCommand in /etc/ssh/sshd_config. Not sure whether the two issues are related.

**Comment by huashengdun** [comment]
To avoid this issue you need to start the server like this :
```
wssh --encoding='utf-8'
```

**Comment by pceBuildMaster** [comment]
Adding the --encoding='utf-8' fixed my similar issue.  Yea!!

I have a custom program configured for the user in /etc/passwd so no interactive shell was give but the program with its own text-based interface:

`jsmit:x:1001:1001:John Smith,,,:/home/jsmith:/usr/local/bin/custom_program
`
A normal ssh worked fine and the 'custom_program' worked and upon exit or a HUB signal user was logged out.  But session hung on webssh until I restarted the server with the encoding param.

Again thx.  Great tool!
