### ISSUE TITLE
[Error] Socket is Closed

### ISSUE THREAD

**Issue by amanhigh** [huashengdun/webssh#165]
We are getting large number of Socket Closed Exceptions.

[E 200702 12:56:09 worker:95] Socket is closed
[E 200702 12:56:09 worker:95] Socket is closed
[E 200702 12:56:09 worker:95] Socket is closed
[E 200702 12:56:09 worker:95] Socket is closed
[E 200702 12:56:09 worker:95] Socket is closed
[E 200702 12:56:09 worker:95] Socket is closed
[E 200702 12:56:09 worker:95] Socket is closed
[E 200702 12:56:09 worker:95] Socket is closed
[E 200702 12:56:09 worker:95] Socket is closed
[E 200702 12:56:09 worker:95] Socket is closed
[E 200702 12:56:09 worker:95] Socket is closed
[E 200702 12:56:09 worker:95] Socket is closed
[E 200702 12:56:09 worker:95] Socket is closed
[E 200702 12:56:09 worker:95] Socket is closed
[E 200702 12:56:09 worker:95] Socket is closed
[E 200702 12:56:09 worker:95] Socket is closed
[E 200702 12:56:09 worker:95] Socket is closed
[E 200702 12:56:09 worker:95] Socket is closed
[E 200702 12:56:09 worker:95] Socket is closed
[E 200702 12:56:09 worker:95] Socket is closed
[E 200702 12:56:09 worker:95] Socket is closed
[E 200702 12:56:09 worker:95] Socket is closed
[E 200702 12:56:09 worker:95] Socket is closed
[E 200702 12:56:09 worker:95] Socket is closed
[E 200702 12:56:09 worker:95] Socket is closed
[E 200702 12:56:09 worker:95] Socket is closed

This is very similar to - https://github.com/huashengdun/webssh/issues/157

**Comment by huashengdun** [comment]
Does his solution https://github.com/huashengdun/webssh/issues/157#issue-604418008 solve your problem?

**Comment by amanhigh** [comment]
Will try it out, however it doesn't always happen but when it happens it gets stuck in the loop.

**Comment by huashengdun** [comment]
@amanhigh 
How is it going?

**Comment by amanhigh** [comment]
Hi @huashengdun ,
Sorry i forgot to reply. Yes this solved our problem and we didn't receive this error till now after that.
