### ISSUE TITLE
How to allow cross station post to submit data

### ISSUE THREAD

**Issue by 1032231418** [huashengdun/webssh#17]
I want to embed it on my platform，How to allow cross station post to submit data？

**Comment by 1032231418** [comment]
大神你好，在哪里设置，允许CSRF  跨站post 提交数据？

**Comment by huashengdun** [comment]
我这里没有这个设置选项，码云上有个版本， 根据我这个二次开发的有这个功能， 你可以去看下。

**Comment by 1032231418** [comment]
@huashengdun  好的，我去码云上看看

**Comment by huashengdun** [comment]
已加了xsrf 选项配置。
