### ISSUE TITLE
运行后无法 control+C 退出？

### ISSUE THREAD

**Issue by sshuangliu** [huashengdun/webssh#170]
![image](https://user-images.githubusercontent.com/38092313/87548351-f7c2ce80-c6de-11ea-9207-b02b1940df00.png)

如图

thanks

**Comment by ochen1** [comment]
试一试 Control C 多按几下 (多raise几个 KeyboardInterrupt Exceptions)。

试一试 Control D， 来 raise 个 EOFError。
