### ISSUE TITLE
Recycling worker

### ISSUE THREAD

**Issue by dengtengfei** [huashengdun/webssh#173]
[I 200826 07:23:00 handler:197] Connecting to xx.xx.xx.xx:22
[I 200826 07:23:00 transport:1746] Connected (version 2.0, client )
[I 200826 07:23:00 transport:1746] Authentication (password) successful!
[W 200826 07:23:01 handler:63] Bad nginx configuration.
[I 200826 07:23:01 web:2162] 200 POST / (193.101.0.20) 697.83ms
[W 200826 07:23:01 web:2162] 403 GET /ws?id=139875787244824 (193.101.0.20) 0.71ms
[W 200826 07:23:04 worker:16] Recycling worker 139875787244824
[I 200826 07:23:04 worker:99] Closing worker 139875787244824 with reason: worker recycled
[I 200826 07:23:04 worker:106] Connection to xx.xx.xx.xx:22 lost

**Comment by huashengdun** [comment]
你使用的webssh是什么版本？
看日志不是最新版本，更新下版本再试试。

**Comment by dengtengfei** [comment]
看了下确实不是最新版，但是用最新版会进制外网访问，提示Public plain http request is forbidden.需要把if not ip_address.is_private:这句注释掉才行吗。

**Comment by dengtengfei** [comment]
我更新到最新版，注释掉if not ip_address.is_private:之后，会报Cross origin operation is not allowed，然后我注释掉
            if not super(IndexHandler, self).check_origin(origin):
                raise tornado.web.HTTPError(
                    403, 'Cross origin operation is not allowed.'
                )
之后，还是报错Recycling worker，确定是1.5.2版本

**Comment by dengtengfei** [comment]
已解决，是我这边PaaS环境的问题，感谢。
另外建议，去掉外网访问限制。

**Comment by huashengdun** [comment]
默认情况下，外网访问http明文请求是限制的，https请求没有限制。
