### ISSUE TITLE
如何让websocket 连接保持更长时间？

### ISSUE THREAD

**Issue by flymark2010** [huashengdun/webssh#18]
Hi,  在登录到远程服务器后，如果不进行任何操作，web终端很快就会关闭（大约50s）。 请问如何可以使连接保持更长时间？ 

谢谢！

**Comment by huashengdun** [comment]
服务器有用nginx吗？

**Comment by flymark2010** [comment]
用了nginx和不用nginx都一样的。  
现在通过设置参数websocket_ping_interval，和websocket_ping_timeout 可以保持长连接了。

**Comment by huashengdun** [comment]
保持长连接有两种方式，一种是TCP keepalive. 还有一种 ping/pong。
我测试下来, chrome和firefox websocket 会不间断发送 TCP keepalive。
所以并不要需要启用tornado的ping机制。

**Comment by flymark2010** [comment]
我测试的时候发现tornado不设置websocket_ping_interval的话，就没法保持长连接，不知道是不是和浏览器相关（我用的也是chrome）。 不过现在通过在tornado后端设置，已经达到保持长连接的目的了。
非常感谢。

**Comment by huashengdun** [comment]
https://superuser.com/questions/302217/chrome-browser-sending-keep-alive-packets
https://bugs.chromium.org/p/chromium/issues/detail?id=27400
你使用的chrome是什么版本，在什么操作系统下？
