### ISSUE TITLE
"Websocket authentication failed" with dual stack

### ISSUE THREAD

**Issue by candlerb** [huashengdun/webssh#183]
(Relates to #71, #87)

This is a minor issue but I thought I'd report it anyway, as it took a while to diagnose.

The problem was with webssh running behind an apache2 reverse proxy on a dual-stack host, accessed from Chrome browser.

```
client ------> (dual stack) apache ----> (127.0.0.1) webssh
```

What happened was:

* For some reason, the browser was preferring the IPv4 address for the server.
    * This was visible as "4" in IPvFoo extension, and also in Apache logs and tcpdump
    * Pressing the "Refresh" button continued to access over IPv4
    * I think this was because the host had been contacted before when it was single-stack, and the browser had decided to stick with this address
* However, when webssh's javascript opened the websocket connection, it was using the IPv6 address.
* As a result, the id token was being rejected with "Websocket authentication failed"

The apache proxy was adding an `X-Forwarded-For:` header, which was the IPv4 address for the HTML fetch and the IPv6 address for the WS fetch - checked with tcpdump on lo0 interface.  (Aside: it seems webssh trusts the X-Forwarded-For header, even though I hadn't set the `--tdstream` option)

Therefore, I could probably work around this problem by disabling the `X-Forwarded-For:` header when proxying.  However there are other services behind this proxy, so it involves a somewhat awkward configuration to disable this header just for webssh.

As I understand it: webssh associates the token to the source IP address, so that when you connect to `/ws?id=xxx` from a different source IP address then it rejects the login.  However, I'm not sure exactly what sort of attack this is supposed to protect from.  Anyone who was able to intercept the token would be able to intercept the original login credentials (which are more valuable), and the token is one-time-use anyway.

I think it would be possible to make the checking a little more lax to be more robust in dual-stack deployments: if the websocket connection comes from an address which is a *different address family* than the original address, then allow it.  Or else it would be nice to have a command-line flag to disable the source checking entirely.

Apart from this minor issue, webssh has been working for me extremely well.  Many thanks for all your hard work!

**Comment by candlerb** [comment]
For reference, the following workaround solves the problem for me:

```
ProxyPass /ssh/ws ws://127.0.0.1:8888/ws
ProxyPass /ssh/ http://127.0.0.1:8888/
ProxyPassReverse /ssh/ http://127.0.0.1:8888/
<Location "/ssh">
    ProxyAddHeaders Off
</Location>
```

I was able to replicate the problem as follows:

* Start with only `A` record in DNS.  Connect to webssh and use it.
* Add `AAAA` record.
* Flush DNS in the upstream cache
* Flush DNS in the client host
    * (macOS) `dscacheutil -flushcache; sudo killall -HUP mDNSResponder`
    * (chrome) `chrome://net-internals/#dns` and press the "Clear host cache" button
* Refresh webssh page (still connects over IPv4)
* Open webssh connection (websocket uses IPv6)

**Comment by huashengdun** [comment]
Interesting, I never knew that webssh websokets prefer IPv6 over IPv4.

To disable xheaders including `X-Forwarded-For` and `X-Real-Ip`, you can start the webssh server like this,
```bash
wssh --xheaders=False
```

**Comment by candlerb** [comment]
Thanks!  Does wssh use the remote IP information for anything else, other than checking that the websocket request came from the same IP as the HTML request?

**Comment by huashengdun** [comment]
Yes, it limits the number of live connections based on the remote IP address.

**Comment by candlerb** [comment]
Ah of course.  So right now I'll have a limit of a total of 20 connections across all clients - I'll need to bump that up.  Thanks for the reminder.

It would be nice to have the per-source connection limit whilst not having the token ID address checking - but for the application I'm using this for (a classroom) it's not going to be a problem.

**Comment by sigma2017** [comment]
Here it is the simplest working nginx.conf without Websocket authenticated failed error:
`server {
        listen 443 http2 ssl;
        #listen 443 ssl;
        server_name webssh.example.com;

        auth_basic "Private Property";
        auth_basic_user_file /etc/nginx/.htpasswd;
        ssl_certificate /etc/letsencrypt/live/wildcard.example.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/wildcard.example.com/privkey.pem;
        location / {
            proxy_pass http://127.0.0.1:8888;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            }
 }
`
