### ISSUE TITLE
Space-bar not work on iPad8 smart keyboard

### ISSUE THREAD

**Issue by LinerSeven** [huashengdun/webssh#189]
Dear Developer.

Your application is very easy to use, but there was a glitch when I tried the SSH connection.

When using the smart keyboard on ipad8, only the spacebar didn't work and I couldn't enter the Linux command options.

I would appreciate a fix, if you don't mind.

Best regards,

**Comment by huashengdun** [comment]
Thanks for reporting this issue here.
Let's see if the developers of https://github.com/xtermjs/xterm.js/issues/1101 can fix this problem.
