### ISSUE TITLE
gbk编码的中文文件支持查看、处理吗？

### ISSUE THREAD

**Issue by anythingwhat** [huashengdun/webssh#19]
@huashengdun ，这个应用，gbk编码的中文文件支持查看、处理吗？

**Comment by huashengdun** [comment]
客户端浏览器是根据ssh服务器的默认编码来解码的。
也就是说，如果你ssh服务器的默认编码是utf-8，浏览器就用utf-8解码。
                  如果你ssh服务器的默认编码是gbk，浏览器就用gbk解码。

所以当你所要处理文件的编码和你ssh服务器的默认编码不一致时，就会出现乱码。

**Comment by anythingwhat** [comment]
@huashengdun 
多谢。实际我是先找到了https://github.com/xsank/webssh.git，后来发现这个project不支持中文非utf-8编码，和这个问题类似https://github.com/xsank/webssh/issues/10。如果ssh服务器上有一个文件名是中文gbk编码的文件，通过webssh终端登录这个服务器的时候，终端会报connection close，查看具体报错信息为“could not decode a text frame as utf-8”。能不能指导下https://github.com/xsank/webssh.git这个project如何修改可以解决这个问题，非常感谢

**Comment by huashengdun** [comment]
不要意思，我对xsank/webssh这个项目不熟悉。
你应该找这个项目的作者xsank寻求帮助。

**Comment by huashengdun** [comment]
@anythingwhat 
`如果ssh服务器上有一个文件名是中文gbk编码的文件，通过webssh终端登录这个服务器的时候，终端会报connection close, 查看具体报错信息为“could not decode a text frame as utf-8”。
 `
服务器上存有中文gbk编码的文件，登录服务器不会导致“终端会报connection close”。
导致客户端wesocket端口，是因为你用了类似cat之类的查看命令。

服务端解决方法如下：
```bash
cat gbk.txt | iconv -f gbk -t utf-8
```

在我的这个应用中，在js里有了两个函数，wssh.set_encoding(encoding), wssh.reset_encoding()。


客户端解决方法如下：

1.设置客户端使用gbk编码，在console中运行，
```JavaScript
wssh.set_encoding('gbk');
```

2. 然后你可以在客户端terminal中可直接运行，能正确显示gbk文件
```bash
cat gbk.txt
```

3. 恢复使用服务器的默认编码，在console中运行，
```JavaScript
wssh.reset_encoding();
```

**Comment by anythingwhat** [comment]
@huashengdun ，非常感谢

**Comment by huashengdun** [comment]
可以先对文件检测编码，然后使用检测获的编码对文件读取成文本文件。
对每个文件都这样做，估计会影响后台效率，尤其大文件。
