### ISSUE TITLE
想自己实现WebSSH的可以参考下这个，功能比较全

### ISSUE THREAD

**Issue by ops-coffee** [huashengdun/webssh#194]
https://github.com/ops-coffee/webssh

实现了如下一些功能

- 交互式命令执行，支持 vim\top 之类的指令
- 所有的操作都会被录像，方便审计回放
- 管理员可以实时监控用户操作，必要的时候给强制踢下线
- 支持 zmodem 协议，可以使用 lrzsz 命令上传下载文件
- 窗口自适应，会根据浏览器窗口大小动态调整后端输出终端大小

**Comment by huashengdun** [comment]
非本项目的问题，关闭了。
