### ISSUE TITLE
wich version of xtermjs ?

### ISSUE THREAD

**Issue by ppacory** [huashengdun/webssh#198]
I've still have this problem :
https://github.com/xtermjs/xterm.js/issues/992 
This bug is correct in xtermjs now, but actually webssh use an old xterm version ? 
wich version webssh use ?

**Comment by huashengdun** [comment]
4.2.0

**Comment by ppacory** [comment]
ok i've ugrade to 4.9.0, still the same problem, in fact it was the font,i change it and it's working.
