### ISSUE TITLE
中文输入问题

### ISSUE THREAD

**Issue by weijiang1994** [huashengdun/webssh#204]
大佬，请教一下手动输入中文需要哪里设置一下？为什么我的项目中不能手动输入中文，同时也不能粘贴，期待你的回复，十分感谢!

**Comment by huashengdun** [comment]
这应该不是webssh本身的问题。

**Comment by weijiang1994** [comment]
> 这应该不是webssh本身的问题。

嗯，可能我没有表达清楚，我的意思是说为什么你的webssh项目可以手动输入中文，而我使用xterm.js的其他项目不能输入中文，不是说我运行你这个项目不能输入中文。我运行你这个项目中文输入、粘贴都正常，但是我自己使用xterm.js的项目就不行，所以想问一下哪里需要配置。

**Comment by huashengdun** [comment]
我没有针对中文对`xterm.js`进行任何配置，可能跟`xterm.js`版本有关系？
这里用的是版本是4.2.0。

**Comment by weijiang1994** [comment]
> 我没有针对中文对`xterm.js`进行任何特殊配置，可能跟`xterm.js`版本有关系？
> 这里用的版本是4.2.0。

好吧，我拿你的版本试一下看看，我用的是3.6版本。

**Comment by huashengdun** [comment]
不能粘贴，应该跟xterm.js版本也没有关系，而是可能你还用了其它特殊的js代码禁止了粘贴功能。
