### ISSUE TITLE
Cross Origin Problem

### ISSUE THREAD

**Issue by Whisper40** [huashengdun/webssh#206]
I started your app on my server like that : `wssh --address='127.0.0.1' --origin="*" --port=8888 --xsrf=False --debug`

And i access it from my computer to the server with my custom address.

The problem is that it does not connect :( 

E.G : It's working without problem from localhost to localhost.
But i need the access from * to my server
![bugwebssh](https://user-images.githubusercontent.com/30440458/106665217-4fa32300-65a6-11eb-944f-32862b01063c.gif)

Do you see what's wrong ?

**Comment by huashengdun** [comment]
What error complained by your webssh server?

**Comment by Whisper40** [comment]
Hello, this is the error that appears on the server 
![image](https://user-images.githubusercontent.com/30440458/106790960-98191a00-6654-11eb-9648-765628430b0b.png)
![image](https://user-images.githubusercontent.com/30440458/106790996-a404dc00-6654-11eb-8996-44318a2756be.png)

**Comment by Whisper40** [comment]
It seems that the problem was on the nginx configuration ! Strange thing
I will close it, thanks for help
