### ISSUE TITLE
the app stops responding

### ISSUE THREAD

**Issue by divyanshumehta** [huashengdun/webssh#21]
I ran the app on my localhost 
```
13:24:45 : ~ $ wssh --address=0.0.0.0 --port=8080 --policy=reject
[I 180827 13:24:53 settings:68] RejectPolicy
[I 180827 13:24:53 main:32] Listening on 0.0.0.0:8080
[I 180827 13:24:57 handler:179] Connecting to 114.216.56.166:22
[I 180827 13:24:57 transport:1687] Connected (version 2.0, client OpenSSH_7.6p1)
[I 180827 13:24:58 transport:1687] Authentication (publickey) failed.
[I 180827 13:24:58 transport:1687] Authentication (password) successful!
[I 180827 13:24:59 web:2162] 200 POST / (127.0.0.1) 1986.78ms
[I 180827 13:24:59 web:2162] 101 GET /ws?id=140671325047312 (127.0.0.1) 0.95ms
[I 180827 13:24:59 handler:244] Connected from 127.0.0.1:34126

```
After putting in my public credentials my browser freezes at black screen
![screenshot from 2018-08-27 13-26-55](https://user-images.githubusercontent.com/16134827/44647967-3bce5c80-a9fd-11e8-8573-4dbf5c4c1b5b.png)

I tried seeing the output in the console in developer tools... I got this there, maybe it is helpful
```ws://localhost:8080/ws?id=140181703862800
main.js:106 The deault encoding of your server is en_IN
7main.js:219 Uncaught RangeError: Failed to construct 'TextDecoder': The encoding label provided ('en_IN') is invalid.
    at FileReader.reader.onloadend (main.js:219)
main.js:239 CloseEvent
```
But it worked some a different ssh server

**Comment by huashengdun** [comment]
Hi divyanshumehta,
Seems it is an encoding error.
Run command `locale` on your ssh server and paste the result here.
This may help me to fix this problem, thank you.

**Comment by huashengdun** [comment]
The result of `locale` on your server is weird.
I see the language, but no encoding information.
Here is my `locale`:
```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by divyanshumehta** [comment]
ok will look into it thanks, you can close the issue if there is no problem within the code. Thanks for the help mate

**Comment by huashengdun** [comment]
It is definitely a bug in my code. For temporarily solve your problem,  
Please run command `python -c "import sys; print(sys.stdout.encoding)"` on your server.
Suppose the result is "UTF-8".
Than change line 219 on your JavaScript file main.js(under webssh/static/js directory)  like that,
`var decoder = new window.TextDecoder("utf-8");`
Actually I am curious what kind of encoding your server is using.

**Comment by huashengdun** [comment]
Hi divyanshumehta,
Can you run a command **locale charmap** on your server for me?
And paste the result here, thank you.

**Comment by huashengdun** [comment]
Good, I think command `locale charmap`  is better than `locale` to get the system default encoding.

**Comment by huashengdun** [comment]
Good, I think command `locale charmap` is better than `locale` for getting the system default encoding.

**Comment by huashengdun** [comment]
Hey  divyanshumehta,
version on pypi updated.
You may try the latest one to see if it fixes the problem correctly.

**Comment by divyanshumehta** [comment]
ok @huashengdun

**Comment by huashengdun** [comment]
Happy to hear that.
I have changed the command `locale charmap`  to `locale` to detect the system encoding.

**Comment by huashengdun** [comment]
Happy to hear that.
I have changed the command  `locale`  to `locale charmap` for detecting the system encoding.

**Comment by divyanshumehta** [comment]
I think we can close this issue
