### ISSUE TITLE
请问docker-compose up启动时如何加入--xsrf=False参数

### ISSUE THREAD

**Issue by hw0805** [huashengdun/webssh#211]
你好，请问是应该在哪个文件里面怎样加入这个参数

**Comment by huashengdun** [comment]
修改下Dockerfile文件里的CMD

**Comment by hw0805** [comment]
好的，感谢

**Comment by hw0805** [comment]
![image](https://user-images.githubusercontent.com/41856210/111584946-8ac98080-87f9-11eb-8f69-30d61fe3fbad.png)
我这样写没效果，麻烦指导下

**Comment by huashengdun** [comment]
不行的话，你可以试试在run.py同级目录下创建个bash文件例如run.sh,  里面添加类似命令 `python run.py --xsrf=False`, 然后再修改Dockerfile文件里的CMD, `["bash", 'run.sh"]`

**Comment by huashengdun** [comment]
不好意思，我上面都没有测试，误导你了。
只能用run命令了，`docker-compose run web -p 8888:8888 python run.py --xsrf=False`
