### ISSUE TITLE
404: not found error

### ISSUE THREAD

**Issue by rambip** [huashengdun/webssh#215]
I tried to host wssh with nginx, but I'm getting a 404 error.

Here is the detail of `curl -v`:
```
*   Trying 192.168.1.26:80...
* Connected to 192.168.1.26 (192.168.1.26) port 80 (#0)
> GET /ssh HTTP/1.1
> Host: 192.168.1.26
> User-Agent: curl/7.76.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Server: nginx/1.14.2
< Date: Mon, 19 Apr 2021 15:11:58 GMT
< Content-Type: text/html; charset=UTF-8
< Content-Length: 69
< Connection: keep-alive
< 
* Connection #0 to host 192.168.1.26 left intact
<html><title>404: Not Found</title><body>404: Not Found</body></html>
```

Does this come from wssh, from python or from nginx ?
Usually, nginx does not give me this error page.

And I'm getting this in the terminal:
[W 210419 16:12:11 web:2243] 404 GET /ssh (192.168.1.30) 2.47ms

I tried with different policies and nginx configs, but that doesn't work.

**Comment by rambip** [comment]
I don't remember exactly what was wrong, but if you have an error caused by a wrong nginx config, here is one that worked for me:

https://github.com/huashengdun/webssh/issues/190

**Comment by randomairborne** [comment]
Scratch that- it loads the config page, but when i click connect, the log
proceeds as normal, but the webssh client freezes.

**Comment by randomairborne** [comment]
After waiting a few minutes, i get a 504 gateway timeout. (sorry for not
editing, i have to use email rather then github)
