### ISSUE TITLE
docker run 403

### ISSUE THREAD

**Issue by lvyinggithub** [huashengdun/webssh#216]
如何docker run的时候传入--fbidhttp=False?

**Comment by lvyinggithub** [comment]
测试build 是成功的,在不二次开发的情况下,支持吗? 不支持只能自己二次开发,如果支持就不重复造轮子了

**Comment by qida** [comment]
CMD是可以覆盖的。
`sudo docker run -d --name ssh -p 8031:8888 qida/webssh python run.py --fbidhttp=False`
