### ISSUE TITLE
404 when running behind nginx

### ISSUE THREAD

**Issue by randomairborne** [huashengdun/webssh#217]
https://github.com/huashengdun/webssh/issues/215 was closed with no solution, what is the cause of this? I have the exact issue.

**Comment by tomasodehnal** [comment]
@randomairborne You might post the nginx config...

I faced the same issue while I was trying to use a subdirectory to forward the traffic. For me it was the missing "/" in the defined location:

- non working:
```
location /console {
  proxy_pass http://127.0.0.1:8888
}
```
- working:
```
location /console/ {
  proxy_pass http://127.0.0.1:8888
}
```

**Comment by fyc119** [comment]
my nginx localtion  
    location /pptssh/ { 
    proxy_pass http://127.0.0.1:8888;
    proxy_http_version 1.1;
    proxy_read_timeout 300;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Real-PORT $remote_port;
}
but  when i  view the  the web http://xxxx.xxx.xx.xx/pptssh/
![image](https://user-images.githubusercontent.com/31608048/131314362-00aba865-35a1-49df-814c-a354568cfa52.png)

it still  404. why?

**Comment by mikryashov** [comment]
> my nginx localtion
> location /pptssh/ {
> proxy_pass http://127.0.0.1:8888;
> proxy_http_version 1.1;
> proxy_read_timeout 300;
> proxy_set_header Upgrade $http_upgrade;
> proxy_set_header Connection "upgrade";
> proxy_set_header Host $http_host;
> proxy_set_header X-Real-IP $remote_addr;
> proxy_set_header X-Real-PORT $remote_port;
> }
> but when i view the the web http://xxxx.xxx.xx.xx/pptssh/
> ![image](https://user-images.githubusercontent.com/31608048/131314362-00aba865-35a1-49df-814c-a354568cfa52.png)
> 
> it still 404. why?

add this one to your Nginx config:
proxy_redirect default;

**Comment by lxh2002** [comment]
just try to add slash at the end of url:
proxy_pass http://127.0.0.1:8888/;
