### ISSUE TITLE
Too many live connections

### ISSUE THREAD

**Issue by liyongtao2000** [huashengdun/webssh#218]

**Comment by liyongtao2000** [comment]
![image](https://user-images.githubusercontent.com/77765955/118768634-d4921e00-b8b1-11eb-97c0-5a7ff4a521b3.png)

**Comment by huashengdun** [comment]
同一个IP连接数过多。

**Comment by LittleDipper** [comment]
> 

想知道问什么会出现这个问题，怎么解决这个问题，不是让你翻译...
