### ISSUE TITLE
如何改变字体颜色

### ISSUE THREAD

**Issue by tianlichunhong** [huashengdun/webssh#221]
只看到改变背景颜色的方法。但是字体颜色如何改变？

**Comment by fakeyw** [comment]
刚推了个pull request加了改字体颜色的参数，有需要可以参考着改下代码

**Comment by huashengdun** [comment]
已merge了fakeyw贡献的代码, 改变字体颜色现在支持了.

**Comment by tianlichunhong** [comment]
使用http://localhost:8888/#fontcolor=red，发现没有任何效果。担心是wssh不是最新的，我通过git clone这个项目，然后Python setup.py install安装的。但是还是没有任何变化。请问什么什么回事？

**Comment by huashengdun** [comment]
pypi上的版本还没更新所以不支持这个功能.

**Comment by tianlichunhong** [comment]
版主好人，希望能更新一下。一直用这个，也挺好用的。或者告诉一下，如何可以安装最新的版本。谢谢！

**Comment by tianlichunhong** [comment]
已经解决了，就是通过git clone这个项目，然后Python setup.py install安装后，重启wssh就可以。只是有时候不可以，不知为何。http://127.0.0.1:8888/#fontcolor=black&bgcolor=white 就可以换成白底黑字了。
