### ISSUE TITLE
我收到了testfight的邀请，但是我无法下载

### ISSUE THREAD

**Issue by jaychoubaby** [huashengdun/webssh#224]
很荣幸收到邀请参与测试，但是我无法下载，提示 所请求的app不可用或者不存在，请问是不是因为国区testfight的原因？可否重新发一个邀请我，我使用国外账号下载试试。
![IMG_0884](https://user-images.githubusercontent.com/26641387/125373380-a0ba0d00-e3b7-11eb-9ceb-99ee9999a98f.PNG)

**Comment by huashengdun** [comment]
你好像搞错了，这个webssh不是android版本的。

**Comment by jaychoubaby** [comment]
> 你好像搞错了，这个webssh不是android版本的。

我没搞错啊，我是IOS啊，iPhone 12pro，但是testfight在国区没法下载了

**Comment by jaychoubaby** [comment]
> 你好像搞错了，这个webssh不是android版本的。

能否重新发个邀请码，我同国外账号接受邀请下载测试版？

**Comment by huashengdun** [comment]
我不是那个app的作者。

**Comment by jaychoubaby** [comment]
> 我不是那个app的作者。

名字一样，我搞错了，不好意思
