### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by rpmohn** [huashengdun/webssh#228]
Hi, I know you said in issue https://github.com/huashengdun/webssh/issues/68#issuecomment-515762854 that changing the font size is not supported. The idea of zooming in/out in the browser doesn't work (at least for me) because it cuts off some lines of text from the terminal. Is font size something you are working on, or something that you think is possible in the future? Thanks!

**Comment by huashengdun** [comment]
It is supported now. See here https://github.com/huashengdun/webssh/pull/233,

**Comment by rpmohn** [comment]
Yes, works brilliantly, thanks for pulling it in!
