### ISSUE TITLE
How can I send / write special keys like Escape etc.?

### ISSUE THREAD

**Issue by frastr** [huashengdun/webssh#229]
e.g. with vim for leaving the insert mode

Thanks in advance

**Comment by frastr** [comment]
For vim i found solution. I can use Ctrl-C for leaving insert mode.

**Comment by huashengdun** [comment]
To me both keys `Esc` and `Ctrl-[` work correctly.

**Comment by frastr** [comment]
I found the reason for my problem. If i deactivate the Firefox and Chromium extension Vimium, then WebSSH works correctly.
Thanks for the good software.
