### ISSUE TITLE
安装成功了，但是启动后报错

### ISSUE THREAD

**Issue by creatorMao** [huashengdun/webssh#231]
![QQ截图20210815001703](https://user-images.githubusercontent.com/24838084/129452696-4692f5ab-8c06-4c93-8487-9d715c694860.jpg)

**Comment by huashengdun** [comment]
图片不完整, 能贴张完整报错的图片吗?

**Comment by creatorMao** [comment]
> 图片不完整, 能贴张完整报错的图片吗?

不好意思，没截全
![QQ截图20210815213544](https://user-images.githubusercontent.com/24838084/129480421-1a4bf750-8af9-4eb9-ae03-d37d8ee354ef.jpg)

**Comment by huashengdun** [comment]
参考下这个 https://stackoverflow.com/questions/62198894/python-cryptography-package-import-error

**Comment by creatorMao** [comment]
> 参考下这个 https://stackoverflow.com/questions/62198894/python-cryptography-package-import-error

好的，我试试
