### ISSUE TITLE
install error in arm64

### ISSUE THREAD

**Issue by yubanmeiqin9048** [huashengdun/webssh#232]
Command "/usr/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-95lgd8u3 --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools>=40.8.0 wheel "cffi>=1.4.1; python_implementation != 'PyPy'"" failed with error code 1 in None

**Comment by omerxx** [comment]
Same here

**Comment by GustavoMotaDF** [comment]
if you use docker in raspberry, try this: https://github.com/GustavoMotaDF/docker-webssh-arm64v8
