### ISSUE TITLE
网络交换机（H3C S5120 V5）连接报错，H3C的V7软件版本正常连接

### ISSUE THREAD

**Issue by woooould** [huashengdun/webssh#238]
[![hgzhT0.png](https://z3.ax1x.com/2021/09/04/hgzhT0.png)](https://imgtu.com/i/hgzhT0)

**Comment by woooould** [comment]
都已经报密码认证成功了，但是还是失败

**Comment by huashengdun** [comment]
Resource shortage, 字面意思是资源不足, 内存不足?

**Comment by huashengdun** [comment]
试试`run.py --encoding='utf-8'`, 看看能不能连接.

**Comment by woooould** [comment]
666666666666666 ,解决了，谢谢大佬
