### ISSUE TITLE
在我的机器上运行，用其他机器的浏览器登录这台机器时失败，查看控制台信息提示worker recycled，怎么处理？

### ISSUE THREAD

**Issue by brysj22952** [huashengdun/webssh#24]
如标题。

**Comment by huashengdun** [comment]
“worker recycled” - 表示客户端没有及时发出websocket连接请求。

**Comment by huashengdun** [comment]
Hi brysj22952,
不知道你使用的是什么浏览器，先前只测试了chrome, firefox.
请更新下代码，测试下是否还有这种情况。

**Comment by siu91** [comment]
> Hi brysj22952,
> 不知道你使用的是什么浏览器，先前只测试了chrome, firefox.
> 请更新下代码，测试下是否还有这种情况。

我是使用 edge 版本 91.0.864.41 
![image](https://user-images.githubusercontent.com/4889213/122323116-2a152580-cf59-11eb-839d-6e0bc01c1851.png)
