### ISSUE TITLE
Private key is not working

### ISSUE THREAD

**Issue by mikryashov** [huashengdun/webssh#242]
![image](https://user-images.githubusercontent.com/91436805/134825544-8793eb78-f8da-487a-801b-93657893656a.png)
How can I fix it?

**Comment by mikryashov** [comment]
This private key is 100% working. When I try putting private key as plain text I have same problem. But over ssh cli this private key working well. Over this web form I can connect to ssh server only when I putting username and password, but I very want using private key. Help me pls. What I need todo for fix it?

**Comment by huashengdun** [comment]
What errors did your webssh (Python console) report?

**Comment by mikryashov** [comment]
Strangely enough, there is nothing in the Python console in debug mode. Moreover, I tried to take dump traffic and did not see any requests to the remote ssh server.
![image](https://user-images.githubusercontent.com/91436805/134866919-3dd32901-8ec8-4391-87f1-6b56c84fdd91.png)

**Comment by mikryashov** [comment]
Example successful debug output when performing authorization by username and password.
![image](https://user-images.githubusercontent.com/91436805/134868216-b43337d9-b57e-4afd-b259-8097c62ce34c.png)

**Comment by mikryashov** [comment]
I resolved my problem. I was need to be change policy value.
