### ISSUE TITLE
Format for passing private key to the wssh.connect function using js

### ISSUE THREAD

**Issue by harsh18262** [huashengdun/webssh#246]
Hello sir,
I am trying to connect using js I am planning to connect a server by directly fetching the data like hostname username private key etc from a database and then connecting to it directly.

i am trying to folow your example:
var opts = {
  hostname: 'hostname',
  port: 'port',
  username: 'username',
  password: 'password',
  privatekey: 'the private key text',
  passphrase: 'passphrase',
  totp: 'totp'
};

but in this when I am passing the private key in text form it is saying invalid key and on the terminal, it says Parsing Key ' ' and then invalid key

I have tried setting the value of hostname var by removing newlines and also by  removing the header and footer parts of the key (---BEGIN OPENSSH KEY----) also but it is not working

**Comment by harsh18262** [comment]
yes, I think openssh version was the problem this time I used the docker image and the key worked.

can also please tell me is there any way to pass the private key using postmessage API of js
this is the format I am using which I found from one of the issues on the repo
    
iframeWindow.postMessage("host" | 22 | username | password ","*");

thanks for your help

**Comment by harsh18262** [comment]
also how do i allow a domain for CORS with the docker

**Comment by n05tr0m0** [comment]
Hello. 
I added the `ed25519` key to SSH, but the program cannot parse it. 
Sends me a message:  Unable to parse the private key.

I added the key according to your hint in the program with the strings BEGIN PRIVATE KEY and END PRIVATE KEY.
But all in vain.
I assume you don't have `ed25519` support?
I bought the program in the AppStore for use on my phone.

**Comment by huashengdun** [comment]
@n05tr0m0 `webssh` is free and the program you bought in the AppStore is not `webssh` here.

**Comment by n05tr0m0** [comment]
> @n05tr0m0 `webssh` is free and the program you bought in the AppStore is not `webssh` here.

I apologize for being confused by similar app names.

Therefore, please consider my comment invalid.

Thank you for your response.
