### ISSUE TITLE
safari not support FormData.get

### ISSUE THREAD

**Issue by CJSoldier** [huashengdun/webssh#25]
in main.js line 373.

```
  function connect_without_options() {
    // use data from the form
    var form = document.querySelector(form_id),
        url = form.action,
        data = new FormData(form),
        pk = data.get('privatekey');
```
I'm writing a small tool supporting multi platform using webview.
I like your webssh, I really need this, please fix it.
I tried to fix, but I got "'_xsrf' argument missing from POST" after calling `ajax_post`.
哥们儿加油。

**Comment by huashengdun** [comment]
你是不是没有使用浏览器？
在post传递数据时，不仅需要post数据包含_xsrf， cookie也需要包含_xsrf。

**Comment by CJSoldier** [comment]
就是用浏览器测的。找到原因了，是因为你在ajax里传的是dom对象而不是json对象。
我把表单序列化成一个json对象，ajax调用时，contentType和processData就不能设置为false了。
我已经提交了PR，你看下。

**Comment by CJSoldier** [comment]
不好意思，提交的代码有问题。没有考虑到privatekey是一个文件。终于知道为什么你要用FormData了。
这个bug还是麻烦你来修复一下吧，我尽力了。

**Comment by huashengdun** [comment]
恩，我在js中使用两种不同类型的Form。

**Comment by huashengdun** [comment]
代码已经更新了，你测试下现在行不行。

**Comment by CJSoldier** [comment]
嗯，我测过了，safari, chrome下都工作的很好。非常感谢。

**Comment by huashengdun** [comment]
很好，现在浏览器 chrome, firefox, safari, opera, edge 似乎都支持了。

**Comment by huashengdun** [comment]
Safari 11.x 也支持了， IE11居然也支持，哈哈。

**Comment by CJSoldier** [comment]
太好了，我看了一下。我的safari是10.1。。。
