### ISSUE TITLE
Store username, port, keyfile and passphrase on webssh server

### ISSUE THREAD

**Issue by Kroups** [huashengdun/webssh#252]
Hi,
First, congrats for your project, this is nice.
I'm a new sys admin and don't know developpement. I have search in the issues and I don't find a response.

So i want store username, port, keyfile and passphrase on the webssh server and connect the the client with https://192.168.2.2/?hostname=192.168.2.4

I reach this in the browser console but i want do the same on the server. Maybe with node.js on webssh server ???

I have changed the index.html but informations are accessible in the source code.

Did you have any idea to do this and so automatize the connexion ???

Thank you for time

**Comment by huashengdun** [comment]
The webssh server is supposed to be used as a proxy. 
I think it is a not a good idea to store the credentials on the webssh server.
