### ISSUE TITLE
I Can't Do Iframe

### ISSUE THREAD

**Issue by utzlol** [huashengdun/webssh#258]
I want to iframe the webssh to my website. But,  i got an error, it says 
[Report Only] Refused to frame 'http://myippublic.com/' because it violates the following Content Security Policy directive: "default-src https: blob: data:". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.

I've tried to use --policy=reject and got an error :
ValueError: Reject policy could not be used without host keys.

I don't have any idea with host keys

**Comment by huashengdun** [comment]
Host keys are normally stored in `~/.ssh/known_hosts`. 
See [tip 3](https://github.com/huashengdun/webssh#tips).

**Comment by utzlol** [comment]
Fixed. I just connect with the server by the same machine and it's generate the known_hosts file.
