### ISSUE TITLE
Unknown ecdsa-sha2-nistp521 

### ISSUE THREAD

**Issue by mengxifl** [huashengdun/webssh#269]
链接防火墙时候报错
/usr/lib/python3.8/site-packages/paramiko/client.py:835: UserWarning: Unknown ecdsa-sha2-nistp521 host key for 10.10.0.6: b'XXXXXXXXXX‘ warnings.warn(

**Comment by huashengdun** [comment]
这个是第一次连接这个host, knowhosts里没有这个host key.
