### ISSUE TITLE
how to enable cross origin completely?

### ISSUE THREAD

**Issue by CJSoldier** [huashengdun/webssh#27]
There's an iframe in my local index.html,like this:

```
<iframe src="localhost:8888"></iframe>
```
I tried to add following code in both class IndexHandler and class WsockHandler:

```
def set_default_headers(self):
        self.set_header("Access-Control-Allow-Origin", "*")
        self.set_header("Access-Control-Allow-Headers", "x-requested-with")
        self.set_header('Access-Control-Allow-Methods', 'GET, PUT, DELETE, OPTIONS')
        self.set_header("Access-Control-Allow-Headers", "access-control-allow-origin,authorization,content-type")
```
but ajax_complete_callback still returned "XSRF cookie does not match POST argument".

Help me please.

**Comment by huashengdun** [comment]
To disable xsrf protection, your can change `xsrf_cookies=True` to `xsrf_cookies=False` in settings.py.
To allow cross-origin traffic, you need to define a method `check_origin` on WsockHandler.

**Comment by CJSoldier** [comment]
Thanks for your quick reply, you saved my time.
`xsrf_cookies=False` works for me.

**Comment by huashengdun** [comment]
Updated:
To disable xsrf protection by passing option `--xsrf=False`,
To enable cross-origin websockets by passing option `--cows=1` or `--cows=2`.

**Comment by huashengdun** [comment]
@larryathey
I recommend you to use this app in this way,

server side:
```bash
wssh --origin='https://test.mazaroth.com
```
client side(browser console):
```
var target_window = window.open('https://webssh.domain.com');
target_window.wssh.connect(ip, port, username, password);
```

**Comment by huashengdun** [comment]
@larryathey
I recommend you to use this app in this way,

server side:
```bash
wssh --origin='https://test.mazaroth.com'
```
client side(browser console):
```
var target_window = window.open('https://webssh.domain.com');
target_window.postMessage('hostname|port|username|password', '*');
// target_window.postMessage(JSON.stringify(['hostname', 'port', 'username', 'password']), '*');
```

**Comment by huashengdun** [comment]
It is pretty like the stuff which the issue opener CJSoldier mentioned in the method `set_default_headers`.

**Comment by huashengdun** [comment]
@larryathey 
Added `CORS` support, let me know if it works or not.

**Comment by larryathey** [comment]
I will try this as soon I can get it started again. I ran "pip install wssh" to update it and now it won't start at all.

**Comment by larryathey** [comment]
$ wssh --help
Traceback (most recent call last):
  File "/usr/local/bin/wssh", line 4, in <module>
    from wssh import client
  File "/usr/local/lib/python2.7/site-packages/wssh/__init__.py", line 1, in <module>
    from server import WSSHBridge
  File "/usr/local/lib/python2.7/site-packages/wssh/server.py", line 9, in <module>
    import gevent
ImportError: No module named gevent

**Comment by larryathey** [comment]
@CJSoldier 
Do you have a working example showing how you were able to get this to work? I'm just working with plain old PHP and Javascript on the sending end. The server on the receiving end simply will not go past the form.

**Comment by huashengdun** [comment]
@larryathey 
So what is the error message?
Make sure you are sending cross-domain ajax post request on the sending end.

**Comment by larryathey** [comment]
I don't have an error message, page is just loading with the form and not submitting. I'm using the example that you provided in the above. This is why I was asking @CJSoldier for an example of how he got it to work because the only other example I have is the target_window.postMessage() example and that's not working. I don't see anything in any documentation that shows it either. So I'm just interested in seeing any working example that I can adapt to what I'm doing.

**Comment by larryathey** [comment]
I'm still not getting any errors, not in the web browser or the terminal window that shows the logging in debug mode.

I see that even when I launch it with --xsrf=False the following hidden form element still exists in the HTML code. Why doesn't --xsrf=False remove this?

<input type="hidden" name="_xsrf" value="2|1133b77a|de20b49db7f5b393eb503da48adafb98|1548182673"/>

I'm not worried about people brute forcing the thing, so this whole xsrf stuff is just preventing me from doing what I want to do.

**Comment by huashengdun** [comment]
Don't worry the xsrf token. 
If you launch the sever with --xsrf=False, the server does not send the xsrf cookie, but it does send the xsrf value through the form. So at last the server will pass the xsrf token checking.   That is the behavior implemented by tornado.

So you are trying the target_window.postMessage() example?
If you don't see any error in your browser, check if there is any error message or warning message on the server end.

**Comment by larryathey** [comment]
I've tried that. I wanted to put the wssh server on a subdomain that matched the same top level domain as the other server and match the port/protocol since that would make the origin match from end to end, but wssh refuses to run on port 443.

When I set the _xsrf input to no value and submit the form, I get this instead of the terminal window.
{"status": null, "id": "140714286386768", "encoding": "US-ASCII"}

When I copy the _xsrf input from the HTML source with and submit the form, I get this instead of the terminal window.
{"status": null, "id": "140714339453072", "encoding": "US-ASCII"}

So to me it looks like --xsrf=False really has no effect on anything.

**Comment by huashengdun** [comment]
Seems you don't use  the target_window.postMessage() example.
`--xsrf=False` tells the server don't send the xsrf cookie, so the server will ignore the the `_xsrf`  token value through the post form.
To prove it, if you pass `--xsrf=True` to the server  or don't pass the option `xsrf` to the server, you will get an 403 error in your browser.

Did you see a warning message like "Recycling worker" in your terminal?

Ok,  now you have got the json result which contains a `id` value, it means post form is success, now you have to use the id to issue a websocket connection and re-implement all the stuff by yourself.
You see, that is why I am recommending you to use the target_window.postMessage() example. Because all the javascript stuff I'v already written in the client side.

**Comment by larryathey** [comment]
I can't get the target_window.postMessage() to do anything, when I call window.open() and then issue the target_window.postMessage('hostname|port|username|password', '*') call, the window opens and the form just sits there, it never submits.

So, I figured I would copy your form into another web page on the sending server and see if --xsrf=False would let me submit the form data from another page, and that's what those errors are from that I just posted.

As far as that ID, I don't know how that's going to do me any good since that's displayed in the browser window trying to connect to the wssh server. If the form post was a success, then I should be looking at a terminal.

**Comment by huashengdun** [comment]
That is probably you run the two lines code together immediately.
You should wait for the page fully loaded, then run the postMessage method.

**Comment by larryathey** [comment]
function sleep(milliseconds) {
      var start = new Date().getTime();
      for (var i = 0; i < 1e7; i++) {
        if ((new Date().getTime() - start) > milliseconds) {
          break;
        }
      }
    }

    function OpenTerminal(WindowName,PList) {
      var TargetWindow = window.open('https://test.mazaroth.com:45443',WindowName);
      sleep(3000);
      TargetWindow.postMessage(PList,'*');
    }

**Comment by huashengdun** [comment]
Don't get complicated. 
Let's test it with the simplest example.

start the server with origin 'same',
```bash
wssh --origin='same'
```

1. open your browser, navigate to 'http://localhost:8888'
2. enter into the console, then run 
```javascript
   var w = open('http://127.0.0.1:8888');
```
3. wait for the page fully loaded, then run 
```javascript
    w.postMessage('hostname|port|username|password', '*'); 
```

4. watch the brower and the terminal to see if text like 'Cross origin frame operation is not allowed' is showing up.

Kill the server, start the server again with origin 'http://localhost:8888',
```bash
wssh --origin='http://localhost:8888'
```
Repeat the four steps above to see if it works.

**Comment by larryathey** [comment]
Suggestion...Add the capability to run this as a CGI behind another web server that can pass the host, port, username and password to it.

**Comment by huashengdun** [comment]
> wssh --origin='same' and wssh --origin='http://localhost:8888' both result with 'Cross origin frame operation is not allowed' after executing w.postMessage('hostname|port|username|password', '*');
> 
> I just did a fresh git clone on another Linux desktop that I used for testing this.
> 
> I'm also using "python main.py --origin=" from the git clone folder but the result is still the same as using wssh.

I'v tested it with **the simplest example** two times and they all work as expected.
I don't know why your testing result is different from mine.
Can you figure out why your testing still complains 'Cross origin frame operation is not allowed' when you launch the server origin 'http://localhost:8888'.
Do you really follow the steps I provided in the example?

**Comment by huashengdun** [comment]
> ```
> function sleep(milliseconds) {
>   var start = new Date().getTime();
>   for (var i = 0; i < 1e7; i++) {
>     if ((new Date().getTime() - start) > milliseconds) {
>       break;
>     }
>   }
> }
> 
> function OpenTerminal(WindowName,PList) {
>   var TargetWindow = window.open('https://test.mazaroth.com:45443',WindowName);
>   sleep(3000);
>   TargetWindow.postMessage(PList,'*');
> }
> ```

Also your there is a potential bug in your sleep function.
You actually don't know how long it will to exhaust the for loop.
You should use `setTimeout` function.

**Comment by larryathey** [comment]
> > wssh --origin='same' and wssh --origin='http://localhost:8888' both result with 'Cross origin frame operation is not allowed' after executing w.postMessage('hostname|port|username|password', '*');
> > I just did a fresh git clone on another Linux desktop that I used for testing this.
> > I'm also using "python main.py --origin=" from the git clone folder but the result is still the same as using wssh.
> 
> I'v tested it with **the simplest example** two times and they all work as expected.
> I don't know why your testing result is different from mine.
> Can you figure out why your testing still complains 'Cross origin frame operation is not allowed' when you launch the server with origin 'http://localhost:8888'.
> Do you really follow the steps I provided in the example?

Yes I really did and I got the 'Cross origin frame operation is not allowed', even with a local instance as well as the remote instance. I tested it with Chromium on Linux and Chrome on Mac OS, same result every time.

**Comment by larryathey** [comment]
> > ```
> > function sleep(milliseconds) {
> >   var start = new Date().getTime();
> >   for (var i = 0; i < 1e7; i++) {
> >     if ((new Date().getTime() - start) > milliseconds) {
> >       break;
> >     }
> >   }
> > }
> > 
> > function OpenTerminal(WindowName,PList) {
> >   var TargetWindow = window.open('https://test.mazaroth.com:45443',WindowName);
> >   sleep(3000);
> >   TargetWindow.postMessage(PList,'*');
> > }
> > ```
> 
> Also there is a potential bug in your sleep function.
> You actually don't know how long it will take to exhaust the for loop.
> You should use `setTimeout` function.

Let's ignore this part, if I can get it to work with your example, then I'll worry about the Javascript in the sending page after that. I copied and pasted your example code and it's not working, so I'm really at a loss for ideas here.

**Comment by huashengdun** [comment]
I'v watched your video carefully.
Seems you are running the javascript code in the page of "https://github.com/huashengdun/webssh/issues/27" instead of "http://localhost:8888".
If you are running the code in the page of "https://github.com/huashengdun/webssh/issues/27", then the origin will be "https://github.com" instead of "http://localhost:8888". But you launch the server with origin  "http://localhost:8888". So you got the result  'Cross origin frame operation is not allowed'.

**Comment by huashengdun** [comment]
> > > ```
> > > function sleep(milliseconds) {
> > >   var start = new Date().getTime();
> > >   for (var i = 0; i < 1e7; i++) {
> > >     if ((new Date().getTime() - start) > milliseconds) {
> > >       break;
> > >     }
> > >   }
> > > }
> > > 
> > > function OpenTerminal(WindowName,PList) {
> > >   var TargetWindow = window.open('https://test.mazaroth.com:45443',WindowName);
> > >   sleep(3000);
> > >   TargetWindow.postMessage(PList,'*');
> > > }
> > > ```
> > 
> > 
> > Also there is a potential bug in your sleep function.
> > You actually don't know how long it will take to exhaust the for loop.
> > You should use `setTimeout` function.
> 
> Let's ignore this part, if I can get it to work with your example, then I'll worry about the Javascript in the sending page after that. I copied and pasted your example code and it's not working, so I'm really at a loss for ideas here.

If you got the result  'Cross origin frame operation is not allowed', it means the server receives the data of the form but it doest not allow this operation. So the sending part totally is working.

**Comment by larryathey** [comment]
> I'v watched your video carefully.
> Seems you are running the javascript code in the page of "http-s://github.com/[/issues/27](https://github.com/huashengdun/webssh/issues/27)" instead of "http://localhost:8888".
> If you are running the code in the page of "http-s://github.com/[/issues/27](https://github.com/huashengdun/webssh/issues/27)", then the origin will be "https://github.com" instead of "http://localhost:8888". But you launch the server with origin "http://localhost:8888". So you got the result 'Cross origin frame operation is not allowed'.

No, if you watched that video, you will see that all I had open was this page and the Chrome console. I started wssh in a terminal window exactly as your example said and then I issued the commands that your example said to issue. The other page that's talking to a completely different instance of webssh on another server doesn't even apply. Watch the video again in full screen and you will see that I'm doing everything on localhost exactly as your example instructed me to do.

**Comment by larryathey** [comment]
> > > > ```
> > > > function sleep(milliseconds) {
> > > >   var start = new Date().getTime();
> > > >   for (var i = 0; i < 1e7; i++) {
> > > >     if ((new Date().getTime() - start) > milliseconds) {
> > > >       break;
> > > >     }
> > > >   }
> > > > }
> > > > 
> > > > function OpenTerminal(WindowName,PList) {
> > > >   var TargetWindow = window.open('https://test.mazaroth.com:45443',WindowName);
> > > >   sleep(3000);
> > > >   TargetWindow.postMessage(PList,'*');
> > > > }
> > > > ```
> > > 
> > > 
> > > Also there is a potential bug in your sleep function.
> > > You actually don't know how long it will take to exhaust the for loop.
> > > You should use `setTimeout` function.
> > 
> > 
> > Let's ignore this part, if I can get it to work with your example, then I'll worry about the Javascript in the sending page after that. I copied and pasted your example code and it's not working, so I'm really at a loss for ideas here.
> 
> If you got the result 'Cross origin frame operation is not allowed', it means the server receives the data of the form but it doest not allow this operation. So the sending part totally is working.

OK, let's go back to the actual topic of this issue reference, "how to enable cross origin completely?". How do we do this? So far, I'm not seeing a working example here or in any documentation.

**Comment by larryathey** [comment]
Sorry for not replying, I modified the code to make it work for my application.

**Comment by huashengdun** [comment]
It's okay. 
I am glad to hear that your application is working finally.
