### ISSUE TITLE
在什么地方修改或取消cookie验证boundary=----验证

### ISSUE THREAD

**Issue by a17797535834** [huashengdun/webssh#271]
在什么地方修改或取消cookie验证boundary=----验证  我要用别的语言调用 但是看不懂python.......

![图片](https://user-images.githubusercontent.com/67455077/154239378-7b03e0e4-7613-4bd4-9a3f-444aa82caf50.png)

**Comment by huashengdun** [comment]
这个boundary是浏览器自动生成的, 因为表单enctype是multipart/form-data。
