### ISSUE TITLE
Will you consider replacing bootstrap&jquery with react?

### ISSUE THREAD

**Issue by CJSoldier** [huashengdun/webssh#28]
Sorry, I'm not saying current webssh is not good. It's beautiful and powerful enough. I really like it especially in vim.

I have a selfish reason for asking this，I'm using ant design, now I have to use an iframe to nest webssh in my small project then adjust iframe height and handle cors problem.

I don't think using webssh via browser is a good idea, because we usually open too many tabs. We cannot use alt+tab to switch apps either. So many people use electron to pack web apps, Electron with React looks like more fashionable.React would be a better choice, because we're not good at css. It seems that React fetch is better than ajax. Please think about it.

**Comment by huashengdun** [comment]
Sounds a cool idea. 
But I have no experience of working with React.

**Comment by CJSoldier** [comment]
Me too. I think someone else will ask this question again because we really need an open source cross-platform ssh desktop app. Once use electron, we prefer React sounds reasonable.
You're good at javascript, don't you? It's easy for you to replace jquery-xterm with react-xterm.
I know rewrite it will take you much time, maybe it's even NOT meaningful to you.
But it's meaningful to us.

**Comment by huashengdun** [comment]
I am a Python developer.
Hope you can find someone who is interested in doing it.
