### ISSUE TITLE
Bad host key issue

### ISSUE THREAD

**Issue by WinfredWuWP** [huashengdun/webssh#280]
使用webssh连接时有时会提示Bad host key. 导致连接不上远程服务器，清空/root/.ssh/known_hosts中的内容后也还是提示相同的错误，后来重启webssh又可以连接上了，不知是何原因？known_hosts文件中也没有远程服务器的IP信息。

**Comment by huashengdun** [comment]
当你清空/root/.ssh/known_hosts中的内容后, webssh并没有清空保存在内存中的known_hosts。
当你重启webssh后, 它会重新读取现有的known_hosts。

**Comment by WinfredWuWP** [comment]
谢谢帮忙分析！可以做到当出现Bad Host Key时自动清除原存储的known_hosts，再重新读取一次known_hosts中的内容不？

**Comment by huashengdun** [comment]
要等你删出掉那条旧的host key记录, 再次读取known_hosts才有意义, 有点费资源, 感觉不是很必要。

**Comment by WinfredWuWP** [comment]
多谢楼主的快速解答。
