### ISSUE TITLE
Define a default character encoding 

### ISSUE THREAD

**Issue by agusdomin** [huashengdun/webssh#281]
Hi, how are you people, here is my problem.

I need to connect to a server with a user that have not shell, so I can't successfully run a function that queries the default encoding because in the handler.py file, its define the next command:
`$SHELL -ilc "locale charmap"` 

When `$SHELL` value of the user that try to connect, its not a shell, its a script.

I determined that the connection made it successfully, but when it goes to config the terminal parameters it cant determine the character encoding

Here is a clue, when a execute command " w " to see all the users that are connected
![image](https://user-images.githubusercontent.com/50929799/162783489-37c3c9b5-bfa3-4eb4-974f-ce20ccdf4058.png)

So I want to know a way to define the default encoding.

Thanks, no problem if there is no response, just looking for some help. Hope i was clear.

**Comment by agusdomin** [comment]
Character encoding i want to use is ISO-8859-15

**Comment by huashengdun** [comment]
`$SHELL` is the shell that the user is using on your server.
It can be any type of shells.
So what are the outputs of `$SHELL -ilc "locale charmap"` and `$SHELL -ic "locale charmap"`?

**Comment by huashengdun** [comment]
> Character encoding i want to use is ISO-8859-15

`wssh --encodin='ISO-8859-15'`

**Comment by agusdomin** [comment]
> `$SHELL` is the shell that the user is using on your server. It can be any type of shells. So what are the outputs of `$SHELL -ilc "locale charmap"` and `$SHELL -ic "locale charmap"`?

I made a mistake describing my problem (will be edit it) sorry, there is no output. 

When someone try to connect with a particular local user in the server, it goes to execute a script that define the `$SHELL` of that local user, and define others variables, so once he is connected, shell's value its not a shell anymore.

So i think that when its get there, once establish connection, and user logged, it could't extract more information from the server. So i determined that providing static parameters will be the solution.

**Comment by agusdomin** [comment]
> > Character encoding i want to use is ISO-8859-15
> 
> `wssh --encodin='ISO-8859-15'`

Thanks, i appreciate it, i thought that solution it will be something like that, sorry, i tried it but didn't know the correct string for de ISO

**Comment by huashengdun** [comment]
> > > Character encoding i want to use is ISO-8859-15
> > 
> > 
> > `wssh --encoding='ISO-8859-15'`
> 
> Thanks, i appreciate it, i thought that the solution it will be something like that, sorry, i tried it but didn't know the correct string for that ISO encoding

Updated, a typo.
