### ISSUE TITLE
chan closed

### ISSUE THREAD

**Issue by syz951127** [huashengdun/webssh#283]
链接空闲一段时间后,就断开链接了。
![image](https://user-images.githubusercontent.com/43607120/168970148-674a77f5-3cd8-42e9-b7fd-7f434499bfb0.png)

**Comment by huashengdun** [comment]
看下这个 https://github.com/huashengdun/webssh/issues/134

**Comment by huashengdun** [comment]
> > 看下这个 #134
> 
> 这个是开启服务端与目标机器的心跳维护吗？ 我现在是有在前端主动与后端有个心跳维护。 我这个提示像是目标ip机器的channel通道断开了

看起来像是你的目标ip机器主动断开的。

**Comment by syz951127** [comment]
> > > 看下这个 #134
> > 
> > 
> > 这个是开启服务端与目标机器的心跳维护吗？ 我现在是有在前端主动与后端有个心跳维护。 我这个提示像是目标ip机器的channel通道断开了
> 
> 看起来像是你的目标ip机器主动断开的。

有办法客户端与目标服务器维护心跳吗？

**Comment by huashengdun** [comment]
可以不间断循环发送一个命令比如 `wssh.send('')`。

**Comment by syz951127** [comment]
> 可以间断循环发送一个命令比如 `wssh.send('')`。

这样的话 界面会展示空格吧？影响用户的使用了

**Comment by huashengdun** [comment]
> > 可以间断循环发送一个命令比如 `wssh.send('')`。
> 
> 这样的话 界面会展示空格吧？影响用户的使用了

`wssh.send('""')`

**Comment by syz951127** [comment]
> > > 可以间断循环发送一个命令比如 `wssh.send('')`。
> > 
> > 
> > 这样的话 界面会展示空格吧？影响用户的使用了
> 
> `wssh.send('""')`

我这里通过连接机器的时候 `ssh -o TCPKeepAlive=yes -o ServerAliveInterval=300`  加了这些参数。目前观察1小时空闲链接是ok的
