### ISSUE TITLE
SSH Tunneling if 2FA is enabled - missing alert asking for Verification Code

### ISSUE THREAD

**Issue by P1xelfehler** [huashengdun/webssh#288]
I did setup the SSH Tunneling with VPN and everything worked great.

Then I installed google authenticator like described here: https://goteleport.com/blog/ssh-2fa-tutorial/

The normal SSH connection still works fine. I will be asked for the Verification Code and I'm in.

But with the tunnelling there is no alert asking for the code and it just fails with "Unable to authenticate to SSH server".

I am using an iPhone 12 with iOS 15.6

**Comment by badverybadboy** [comment]
I am getting the same issue using google authenticator. I think the issue is that there is no handler for google-authenticator. or that the interface never passes the code to ssh_client

**Comment by badverybadboy** [comment]
Issue 

> I did setup the SSH Tunneling with VPN and everything worked great.
> 
> Then I installed google authenticator like described here: https://goteleport.com/blog/ssh-2fa-tutorial/
> 
> The normal SSH connection still works fine. I will be asked for the Verification Code and I'm in.
> 
> But with the tunnelling there is no alert asking for the code and it just fails with "Unable to authenticate to SSH server".
> 
> I am using an iPhone 12 with iOS 15.6

Hi 

I seem to have figured out the issue. It seems that it doesn't work properly with interactive-mode so if in your /etc/ssh/sshd_config you add KbdInteractiveAuthentication yes and then restart both ssh and sshd it should work

**Comment by P1xelfehler** [comment]
I just tried it in sshd_config but still the same.

Also the man page says that it is an alias for the deprecated ChallengeResponseAuthentication and that was already set to yes for me. The default for KbdInteractiveAuthentication is yes anyway.

**Comment by P1xelfehler** [comment]
It works now without doing anything for some reason :)
Maybe it was one of the reboots lately that fixed it plus what you said @badverybadboy what should be updated in sshd_config.

**Comment by Geralt1209** [comment]
I was getting the same errors with google authenticator and after days of investigating, I finally figured out that the even though the totp was passed to my server, paramiko continued trying to connect ssh using basic username, password pairs. That is,  somehow entering the totp does triggered 2-factor authentication process. It all went well after changing two_factor = False to two_factor = True inside the (...../webssh/handler.py) file of line 65.

**Comment by biswaKL** [comment]
It is now working for me now.
How to fix it I need little help please, I am able to login from putty but its not working from the UI

**Comment by abcbarryn** [comment]
In /etc/ssh/sshd_config set this option
AuthenticationMethods=keyboard-interactive
or optionally
AuthenticationMethods=publickey keyboard-interactive
which will allows login with only a public key, or
AuthenticationMethods=publickey,keyboard-interactive
(note the comma) which will require a public key AND the password AND the one time password
if you are using webssh and one time passwords do NOT use
AuthenticationMethods=password
it causes webssh to break.
