### ISSUE TITLE
any way to lock the port to 22 by default?

### ISSUE THREAD

**Issue by pingloop22345** [huashengdun/webssh#29]
If no port is given by the user, use port 22.

Tried some things but without result, because I have very little experience with jqeury.

**Comment by huashengdun** [comment]
Hi pingloop22345,
I have updated the code and set default port as 22 https://github.com/huashengdun/webssh/commit/fdcf1718c110462ee682157e64e7b45c3d9211af

**Comment by pingloop22345** [comment]
I build the new version from source. but the changes in HTML don't take effect as far as I can see.

**Comment by huashengdun** [comment]
To update it, run
```bash
pip install -U https://github.com/huashengdun/webssh/archive/master.zip
```

**Comment by huashengdun** [comment]
Also you may need to clear the browser cache.
