### ISSUE TITLE
fail to load font on Windows 10

### ISSUE THREAD

**Issue by mengfanbocz** [huashengdun/webssh#295]
browser console shows the following error message:
Failed to load resource: the server responded with a status of 404 (Not Found)        static%0Css%0Fonts%0Font.ttf:1

seems the path is incorrect (should be static/Css/Fonts/Font.ttf), the separator should be "/" instead of "%0%

can anybody help?
![2022-10-17_093008](https://user-images.githubusercontent.com/86814551/196070616-70141d43-7059-46c2-8cb7-5e327612ef93.png)

**Comment by mengfanbocz** [comment]
more info from wssh output:

![image](https://user-images.githubusercontent.com/86814551/196078005-3fd486ff-9c6f-420c-9cf8-bedeabd6b052.png)

**Comment by mengfanbocz** [comment]
got it ... it works after changing "os.path.join(*(dirs + [filename]))" to " '/'.join(dirs + [filename])" in line 73 of settings.py
![2022-10-17_112040](https://user-images.githubusercontent.com/86814551/196082853-63b54d90-1fd2-43db-b8ae-7b5d17c21b0e.png)

**Comment by huashengdun** [comment]
This is a bug window only. Can you make a pull request?

**Comment by huashengdun** [comment]
https://github.com/huashengdun/webssh/commit/ee24eb7f65e3bd3e2d49f630a1a8af4339bb4c0c
