### ISSUE TITLE
终端页面的内容不能满屏显示，只能显示24行内容

### ISSUE THREAD

**Issue by aixocm** [huashengdun/webssh#3]
![image](https://user-images.githubusercontent.com/12877836/35429586-9fbb4dac-02af-11e8-87a0-489608d84a34.png)

**Comment by aixocm** [comment]
Thanks,I sloved it!

**Comment by huashengdun** [comment]
Hi aixocm, can you create a pull request?

**Comment by huashengdun** [comment]
Hi aixocm, can you create a pull request?

**Comment by huashengdun** [comment]
Thanks for your pull request.
Do you have a more general way to set the term with appropriate number of rows?

**Comment by hequan2017** [comment]
Also pay attention to the problem

**Comment by huashengdun** [comment]
OK, I'v updated the code. 
Welcome to test.
