### ISSUE TITLE
OSS License compatibility question

### ISSUE THREAD

**Issue by Ashley123456789** [huashengdun/webssh#324]
There’s some possible confusion on the license of your repository when you combine other open-source code. 

The module `tests/sshserver.py` claims its license as the GNU Lesser General Public License 2.1 (**LGPL-2.1**). However, the license of your whole project is shown as **the MIT license** in LICENSE, i.e., **less strict** than LGPL-2.1 on license terms, which has impacted the whole license compatibility in your repository and may bring legal and financial risks.

You can select another proper license for your repository, or update this license with exceptions for specific modules.

**Comment by huashengdun** [comment]
Thanks for your advice.
Solved this problem.
