### ISSUE TITLE
登录安装了AIX系统的小型机，backspace键和delete键不能正常使用

### ISSUE THREAD

**Issue by anythingwhat** [huashengdun/webssh#33]
@huashengdun ，hi，用这个app登录安装了AIX系统的小型机的时候，backspace键和delete键不能正常使用，左方向键<-可以删除，但删除后，再按字母a或者i才能继续输入，像是进入了vi模式。安装linux系统的x86没有这个问题。麻烦看看怎么回事，谢谢。

**Comment by huashengdun** [comment]
AIX应该是使用了an Enhanced X-Windows terminal emulator - aixterm. 
所以xterm.js不能很好支持。请看下面链接，
https://www.ibm.com/support/knowledgecenter/en/ssw_aix_71/com.ibm.aix.cmds6/xterm.htm
https://www.ibm.com/support/knowledgecenter/ssw_aix_71/com.ibm.aix.cmds1/aixterm.htm

**Comment by huashengdun** [comment]
我没用过AIX, 你可以试试在你的AIX系统用户profile里添加一个命令，`export TERM=xterm `, 看看有没有效果。

**Comment by anythingwhat** [comment]
export TERM=xterm没有效果，还是非常感谢。

**Comment by huashengdun** [comment]
你先去掉 `export TERM=xterm` 这个配置， 回复原来的状态。
然后运行 `echo $TERM` 看看是什么结果（很好奇AIX默认的terminal type是什么）。
然后运行 `export TERM=xterm`， 再运行  `echo $TERM` 看看有没有生效。

这个页面，https://serverfault.com/questions/91760/what-is-the-best-term-type-on-aix-for-use-with-putty-and-which-putty-settings-s
可能对你有帮组。

**Comment by anythingwhat** [comment]
去掉 export TERM=xterm，运行echo $TERM打印出vt100。在.profile设置export TERM=xterm，运行echo $TERM打印出xterm，生效了。

**Comment by huashengdun** [comment]
http://ps-2.kev009.com/AIXtip/stty_bksp.htm
https://www.linuxquestions.org/questions/aix-43/force-delete-key-to-work-in-aix-ksh-583437/

**Comment by anythingwhat** [comment]
在.profile里设置stty erase ^?，backspace键可以正常使用了，感谢！

**Comment by huashengdun** [comment]
delete键, 如果还没解决的话，google下应该也能解决的。
关闭这个issue了。

**Comment by futurecad** [comment]
https://github.com/xtermjs/xterm.js/issues/4278

这个方案也可以
