### ISSUE TITLE
ipv6单栈debian 11上ssh连接不上，提示Websocket authentication failed.

### ISSUE THREAD

**Issue by imrzyang** [huashengdun/webssh#330]
ipv6单栈debian 11上ssh连接不上，提示Websocket authentication failed.
如下是日志
```
[I 230205 15:18:20 handler:452] Connecting to localhost:22
[I 230205 15:18:21 transport:1871] Connected (version 2.0, client OpenSSH_8.4p1)
/usr/local/lib/python3.9/dist-packages/paramiko/client.py:851: UserWarning: Unknown ecdsa-sha2-nistp256 host key for localhost: b'1e70b336fc8a75ecee4cdc04008a5a4a'
  warnings.warn(
[I 230205 15:18:21 handler:86] Trying password authentication
[I 230205 15:18:21 transport:1871] Authentication (password) successful!
[I 230205 15:18:21 web:2271] 200 POST / (2400:cb00:581:1024::ac47:d2ef) 446.01ms
[I 230205 15:18:23 web:2271] 101 GET /ws?id=deGqzcfPBNEAYSLehg4_Dxh2CSELFmTrD6M1A8QuGso (2400:cb00:581:1024::ac47:d20b) 0.91ms
[I 230205 15:18:23 handler:537] Connected from 2400:cb00:581:1024::ac47:d20b:33848
[I 230205 15:18:23 handler:597] Disconnected from 2400:cb00:581:1024::ac47:d20b:33848
[W 230205 15:18:24 worker:33] Recycling worker deGqzcfPBNEAYSLehg4_Dxh2CSELFmTrD6M1A8QuGso
[I 230205 15:18:24 worker:123] Closing worker deGqzcfPBNEAYSLehg4_Dxh2CSELFmTrD6M1A8QuGso with reason: worker recycled
[I 230205 15:18:24 worker:131] Connection to localhost:22 lost
```

**Comment by hrzyang** [comment]
我运行的命令是`wssh --port=8888 --sslport=2096 --certfile='/root/cert.crt' --keyfile='/root/private.key' --xheaders=False`,只要后面加`--policy=reject`参数，就会报错”“，以至于无法启动。
```
root@srv27659:~# wssh --port=8888 --sslport=2096 --certfile='/root/cert.crt' --keyfile='/root/private.key' --xheaders=False --policy=reject
[I 230205 15:21:39 settings:125] RejectPolicy
Traceback (most recent call last):
  File "/usr/local/bin/wssh", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/webssh/main.py", line 47, in main
    app = make_app(make_handlers(loop, options), get_app_settings(options))
  File "/usr/local/lib/python3.9/dist-packages/webssh/main.py", line 16, in make_handlers
    policy = get_policy_setting(options, host_keys_settings)
  File "/usr/local/lib/python3.9/dist-packages/webssh/settings.py", line 126, in get_policy_setting
    check_policy_setting(policy_class, host_keys_settings)
  File "/usr/local/lib/python3.9/dist-packages/webssh/policy.py", line 47, in check_policy_setting
    raise ValueError(
ValueError: Reject policy could not be used without host keys.
```

**Comment by hrzyang** [comment]
居然又可以连上了，真的很奇怪

**Comment by huashengdun** [comment]
> 我运行的命令是`wssh --port=8888 --sslport=2096 --certfile='/root/cert.crt' --keyfile='/root/private.key' --xheaders=False`,只要后面加`--policy=reject`参数，就会报错”“，以至于无法启动。
> 
> ```
> root@srv27659:~# wssh --port=8888 --sslport=2096 --certfile='/root/cert.crt' --keyfile='/root/private.key' --xheaders=False --policy=reject
> [I 230205 15:21:39 settings:125] RejectPolicy
> Traceback (most recent call last):
>   File "/usr/local/bin/wssh", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.9/dist-packages/webssh/main.py", line 47, in main
>     app = make_app(make_handlers(loop, options), get_app_settings(options))
>   File "/usr/local/lib/python3.9/dist-packages/webssh/main.py", line 16, in make_handlers
>     policy = get_policy_setting(options, host_keys_settings)
>   File "/usr/local/lib/python3.9/dist-packages/webssh/settings.py", line 126, in get_policy_setting
>     check_policy_setting(policy_class, host_keys_settings)
>   File "/usr/local/lib/python3.9/dist-packages/webssh/policy.py", line 47, in check_policy_setting
>     raise ValueError(
> ValueError: Reject policy could not be used without host keys.
> ```
选择使用Reject policy，know_hosts必须得有记录
