### ISSUE TITLE
CRT等超级终端可以登录旧版华为路由器设备，但是webssh登录时登录页面报chan closed错误。

### ISSUE THREAD

**Issue by xl10102** [huashengdun/webssh#336]
显示认证成功，任然报chan close错误，以下是报错日志：
[I 230307 17:50:06 settings:125] WarningPolicy
[I 230307 17:50:06 main:38] Listening on 192.168.106.119:8888 (http)
[I 230307 17:50:27 web:2239] 200 GET / (192.168.106.119) 6.01ms
[I 230307 17:51:28 web:2239] 200 GET / (192.168.106.119) 2.00ms
[I 230307 17:51:29 web:2239] 200 GET /static/css/bootstrap.min.css (192.168.106.119) 833.31ms
[I 230307 17:51:29 web:2239] 200 GET /static/css/fullscreen.min.css (192.168.106.119) 3.99ms
[I 230307 17:51:29 web:2239] 200 GET /static/js/jquery.min.js (192.168.106.119) 9.00ms
[I 230307 17:51:29 web:2239] 200 GET /static/js/popper.min.js (192.168.106.119) 13.00ms
[I 230307 17:51:29 web:2239] 200 GET /static/js/bootstrap.min.js (192.168.106.119) 16.00ms
[I 230307 17:51:29 web:2239] 200 GET /static/css/xterm.min.css (192.168.106.119) 20.00ms
[I 230307 17:51:29 web:2239] 200 GET /static/js/xterm-addon-fit.min.js (192.168.106.119) 8.00ms
[I 230307 17:51:29 web:2239] 200 GET /static/js/main.js (192.168.106.119) 10.86ms
[I 230307 17:51:29 web:2239] 200 GET /static/js/xterm.min.js (192.168.106.119) 8.01ms
[I 230307 17:51:29 web:2239] 200 GET /static/img/favicon.png (192.168.106.119) 4.00ms
[I 230307 17:51:30 handler:454] Connecting to 10.252.32.143:22
[I 230307 17:51:30 transport:1871] Connected (version 2.0, client HUAWEI-1.5)
D:\Program Files\python3\lib\site-packages\paramiko\client.py:851: UserWarning: Unknown ssh-rsa host key for 10.252.32.143: b'c2ac2d534e65164822d880717f4c65d4'
  warnings.warn(
[I 230307 17:51:30 handler:86] Trying password authentication
[I 230307 17:51:31 transport:1871] Authentication (password) successful!
[I 230307 17:51:31 transport:1871] Disconnect (code 2): The connection is closed by SSH Server
    Current FSM is Disconnect
[I 230307 17:51:31 handler:434] Unable to open channel.
[I 230307 17:51:31 handler:434] SSH session not active
[W 230307 17:51:31 handler:446] Could not detect the default encoding.
[I 230307 17:51:31 web:2239] 200 POST / (192.168.106.119) 1506.39ms
[I 230307 17:51:31 web:2239] 101 GET /ws?id=PmHYTZe7OJpwLy_Hhs-EetlHbj8Srw3_5RwD8RfmHrE (192.168.106.119) 1.00ms
[I 230307 17:51:31 handler:539] Connected from 192.168.106.119:1539
[I 230307 17:51:31 worker:123] Closing worker PmHYTZe7OJpwLy_Hhs-EetlHbj8Srw3_5RwD8RfmHrE with reason: chan closed
[I 230307 17:51:31 worker:131] Connection to 10.252.32.143:22 lost
[I 230307 17:51:31 handler:599] Disconnected from 192.168.106.119:1539

**Comment by huashengdun** [comment]
试试在webssh服务启动时加个参数 `wssh --encoding='utf-8'` 。

**Comment by huashengdun** [comment]
这是因为一些老设备不支持ssh多个channel同时打开。修改代码有些麻烦，简单解决方法启动服务加encoding参数。
