### ISSUE TITLE
How to add the port of the ssh server in the url

### ISSUE THREAD

**Issue by bruis0819** [huashengdun/webssh#338]
example : i want to access https://127.0.0.1:9443/?hotname=192.168.1.253 ,but 192.168.1.253 This server ssh port is 9992,Excuse me, how can I access

**Comment by huashengdun** [comment]
`https://127.0.0.1:9443/?hotname=192.168.1.253&port=9992`

**Comment by bruis0819** [comment]
Think's

Shengdun Hua ***@***.***> 于2023年3月19日周日 08:56写道：
