### ISSUE TITLE
能不能在app里增加连接只开启了telnet服务的机器的功能

### ISSUE THREAD

**Issue by anythingwhat** [huashengdun/webssh#34]
hi，这个app通过ssh连接服务器，我这里有许多服务器，有的服务器没有开启ssh服务，只开启了telnet服务，能不能在app里增加连接只开启了telnet服务的机器的功能？感谢！

**Comment by huashengdun** [comment]
telnet明文传输不安全。

**Comment by anythingwhat** [comment]
这些服务器都在内网，而且是测试环境，telnet明文传输不安全的问题可以不考虑

**Comment by huashengdun** [comment]
你可以试试这个 https://github.com/jquast/telnetlib3

**Comment by anythingwhat** [comment]
多谢
