### ISSUE TITLE
Cursor is invisible on white background

### ISSUE THREAD

**Issue by bhubr** [huashengdun/webssh#345]
Hello,

I believe it is not possible, as of now, to change the xterm's cursor color in webssh.
I sometimes use a e-ink device to ssh to my laptop, and a white background is more comfortable in this case.
If I open `http://192.168.1.x:8888/?fontColor=black&bgColor=white`, some tools (e.g. Vim) are barely usable because the cursor is white, hence invisible.

I have a [commit on my fork](https://github.com/bhubr/webssh/commit/a1c0ded18ab9eeb9de82c0712611fc4408c82a37) to address this issue, allowing to pass a cursor color via the `cursor` query param, otherwise using the `fontColor` param, if provided, as cursor color.

I can submit a PR if needs be.

Thanks for this, and for all the work you put in this project!

**Comment by bhubr** [comment]
Thanks for your reply,
I just submitted a PR.

**Comment by huashengdun** [comment]
Merged, thanks.

**Comment by bhubr** [comment]
Thanks you!
