### ISSUE TITLE
setup.py egg_info did not run successfully

### ISSUE THREAD

**Issue by gzrazor** [huashengdun/webssh#349]
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\\******\AppData\Local\Temp\pip-install-y8uhuqvq\webssh_f31e09927d654426b4e83dc3e28d246a\setup.py", line 3, in <module>
          from webssh._version import __version__ as version
      ModuleNotFoundError: No module named 'webssh'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by huashengdun** [comment]
What OS? 
Which version of Python?
How you installed it?

**Comment by gzrazor** [comment]
> What OS? Which version of Python? How did you install it?
Win10 x64 pro without administrator privileges, using embedded Python 3.11
and there are no error in another win10 with installer Python 3.11

**Comment by huashengdun** [comment]
Found a similar issue here https://github.com/pypa/pip/issues/11526
