### ISSUE TITLE
Seems not to be able to copy text from web console

### ISSUE THREAD

**Issue by baiwfg2** [huashengdun/webssh#35]
The `copy` and `cut` button are disabled.

![image](https://user-images.githubusercontent.com/5157680/47988546-73eccc80-e11d-11e8-83d0-9a65bc6feb08.png)

@huashengdun

**Comment by baiwfg2** [comment]
BTW, very useful tool !

**Comment by baiwfg2** [comment]
Something very  strange ! I use `screen` in web console. Before I enter `screen` session, the text can be copied. After entering a `screen session`, the text can be copied and cut for a few seconds, after that it can't any longer.  See the gif file

![webssh-cannot-copy-in-screen](https://user-images.githubusercontent.com/5157680/48056649-2fc8fd00-e1ed-11e8-902b-1afedf504c3b.gif)

> Pay attention to my cursor which points to `copy ctrl+c` and `cut ctrl+x`

**Comment by huashengdun** [comment]
Interesting!

I'v tested with a screen session and reproduced the error.
Seems xterm.js can't properly handle 'right clicking' event within a screen session.

![screen](https://user-images.githubusercontent.com/909962/48111926-e4672b00-e28e-11e8-88f6-9314faad3f94.png)

Even I update this app with latest xterm.js, but the error still remains.
You may report this error to https://github.com/xtermjs/xterm.js/ directly.

**Comment by huashengdun** [comment]
https://github.com/xtermjs/xterm.js/issues/307

**Comment by baiwfg2** [comment]
Oh, many thanks !
