### ISSUE TITLE
Password stored in plain text

### ISSUE THREAD

**Issue by tuxhamb** [huashengdun/webssh#37]
Form details are saved in local storage. I think it is unusual to save password in this way, probably better to let the browser do it and just remember the hostname, port and username.

![image](https://user-images.githubusercontent.com/44919784/48315330-ab9bbe80-e5cc-11e8-8975-81dfee847dbd.png)

**Comment by huashengdun** [comment]
I think you are right.
Can you make a pull request for this issue?

**Comment by huashengdun** [comment]
Merged, thank you.
