### ISSUE TITLE
Connection to 139.199.210.171:8080 is not allowed.

### ISSUE THREAD

**Issue by bluesnail95** [huashengdun/webssh#39]
I login in https://webssh.huashengdun.org/.and I filled the form,The index page showed "Connection to 139.199.210.171:22 is not allowed"; do you know the reason.I had tried "telnet 139.199.210.171 22" is ok.

**Comment by huashengdun** [comment]
I am using `RejectPolicy` as the missing host key policy.
So any host is not in my `known_hosts` will be rejected.
See the last tip in README.
