### ISSUE TITLE
大神您好，请问怎么设置非本地也可以访问服务器呢?

### ISSUE THREAD

**Issue by xbotio** [huashengdun/webssh#40]
大神您好，我配置好了站点，在本地127.0.0.1:8888可以访问，那么我怎么设置非本地也可以通过 服务器IP（或者域名）加端口的方式访问这个页面呢？谢谢了

**Comment by xbotio** [comment]
谢谢回复，我是直接在windows vps里装的python，然后装的webssh的服务。运行wssh后，我本地IP:8888访问VPS，显示403 Forbidden。VPS里的命令行监听显示public plain http request is forbidden,按照您说的deployment 运行wssh --port=8080 --sslport=4433 --certfile='cert.crt' --keyfile='cert.key' --xheaders=False --policy=reject也有错误。麻烦能具体说下怎么设置吗？我是这个行业的业余爱好者，水平有限，谢谢了。

**Comment by huashengdun** [comment]
如果部署到vps上去的话，你要有域名及证书。
如果只是测试的话，完全可以在本地或者局域网内搞。

以下面这个命令方式运行，可以暂时让wssh接受公开的http请求，不过**不安全**。
`wssh --port=8080 --fbidhttp=False`

**Comment by xbotio** [comment]
大神，照你说的可以了。非常感谢！
