### ISSUE TITLE
running behind nginx on ubuntu 18.04 / several issues on initial start

### ISSUE THREAD

**Issue by fsantiago07044** [huashengdun/webssh#41]
hello,

i followed your guide on quickstart, running behind nginx. i have a couple issues so far:

1.> when starting wssh command line reports error no host key found; started as per your readme example for running behind nginx. does this mean my host's ssh private key? i did create one (RSA) so I'm unsure what's going on here.

2.> when i browse to it in my browser, it seems to be missing its css. the page is missing any and all graphics / styling. 

3.> when i attempt connecting to a host which requires key based auth, and watch the command line log output, it states connection successful but my browser view never goes to a shell session. and the log then reports connection dropped / worker recycled. 

so what am i doing wrong? Thanks.

**Comment by huashengdun** [comment]
Hi,

1. The host keys are the public keys of your ssh servers.

2. Probably it is a problem of your Nginx config.

3. Not sure, but I guess it is also a problem which comes from your Nginx config.

I recommend you to play around this app for just running it as a stand-alone server to get started.

**Comment by huashengdun** [comment]
Hi,

1. The host keys are the public keys of your ssh servers which are stored in your `~/.ssh/known_hosts`.

2. Probably it is a problem of your Nginx config.

3. Not sure, but I guess it is also a problem which comes from your Nginx config.

I recommend you to play around this app by just running it as a stand-alone server to get started.

**Comment by fsantiago07044** [comment]
fine it works directly if i turn off the reject policy and looks normal in browser. 

i need it to connect to any ssh host. i will password protect the site in nginx to prevent outsider's use. so the reject policy won't be needed by me than right?

and i would need help getting it up in nginx correctly. if you can...otherwise i'll just putz around.

also, the browser terminal session doesn't have any provision for pasting of text into the terminal? That's a bummer. can this be added?

**Comment by huashengdun** [comment]
If you don't have any host keys in advance and use `Reject` policy, you will not able to start this app.
So I doubt how can you run it in that way.

You can use HTTP Basic Authentication if you need to project your site.

You can use right click to copy and past text.
