### ISSUE TITLE
Can't seem to start the console actions to work

### ISSUE THREAD

**Issue by jpcaldwell30** [huashengdun/webssh#42]
I'm trying to use the app without the login/connect/authentication page and have it just jump straight to the logged in terminal. I have imbedded it in a self hosted front end for my home automation system and it is only accessible over VPN so I'm not worried about sign on security. I thought the consol options might allow me to hardcode the connection expected by the front end but I can't seem to get it to work. 

>>> import webssh
>>> webssh.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'connect

**Comment by huashengdun** [comment]
Section `Use console` is for the browser console.
