### ISSUE TITLE
如何解决跨域问题？

### ISSUE THREAD

**Issue by guohongze** [huashengdun/webssh#45]
我有自己的管理平台，希望使用webssh的服务，但不需要webssh自带那个界面，因为我需要连接CMDB读取信息。
我尝试了几次，关闭了csrf保护以后再跨域连接websocket仍然会报403，使用webssh自带的web页面就没问题。
希望楼主指点一下，或是在以后的迭代里提供前后分离的解决方案。
日志
[I 190104 21:21:30 handler:301] Connecting to 192.168.47.101:22
[I 190104 21:21:30 transport:1746] Connected (version 2.0, client OpenSSH_7.4)
[I 190104 21:21:30 transport:1746] Authentication (publickey) failed.
[I 190104 21:21:30 transport:1746] Authentication (password) successful!
[I 190104 21:21:30 web:2162] 200 POST / (192.168.47.1) 248.86ms
[W 190104 21:21:30 web:2162] 403 GET /ws?id=140128766891728 (192.168.47.1) 1.60ms
[W 190104 21:21:33 worker:16] Recycling worker 140128766891728
[I 190104 21:21:33 worker:99] Closing worker 140128766891728 with reason: worker recycled
[I 190104 21:21:33 worker:106] Connection to 192.168.47.101:22 lost

**Comment by guohongze** [comment]
我的前台代码在webssh中测试过了，只要在webssh里启动不跨域就可以正常使用。

**Comment by guohongze** [comment]
找到解决方案了，重写了WsockHandler
class WsockHandler(MixinHandler, tornado.websocket.WebSocketHandler):

    def initialize(self, loop):
        super(WsockHandler, self).initialize(loop)
        self.worker_ref = None
    def check_origin(self, origin):
        return True

**Comment by huashengdun** [comment]
https://github.com/huashengdun/webssh/issues/27
