### ISSUE TITLE
能否支持url中传递参数，然后直接连接到终端

### ISSUE THREAD

**Issue by yanxiaowuchris** [huashengdun/webssh#47]
我所希望的使用方式：
在我的web页面中，提供一个按钮，点击后，使用下面的方式
window.open("http://wsship:port/api?hostname=xx&port=xx&username=xx&password=xxx")
参数最好使用post，最好使用某种方式加密。

不知能否支持上述需求，谢谢！

**Comment by huashengdun** [comment]
你可以这样使用，不支持跨域，
var target_window = window.open('https://webssh.domain.com');
target_window.wssh.connect(ip, pot, username, password);

或者直接合并， 
window.open('https://webssh.domain.com'）。wssh.connect(ip, pot, username, password);

**Comment by huashengdun** [comment]
你可以这样使用，不支持跨域，
var target_window = window.open('https://webssh.domain.com');
target_window.wssh.connect(ip, port, username, password);

或者直接合并，
window.open('https://webssh.domain.com').wssh.connect(ip, port, username, password);

**Comment by yanxiaowuchris** [comment]
好的，我试试看，非常感谢，刚才下拉最新的代码

**Comment by huashengdun** [comment]
已支持跨域链接了， 只要服务端有这个`origin`就行。
服务器启动时传个跨域的域名网址， 
```bash
wssh --origin='http://www.example.com'
```

**Comment by huashengdun** [comment]
已经加上了通过url传递参数的功能。

**Comment by sky800719** [comment]
能否支持命令也拼接到url串里面，登录后，直接执行url里面的命令，谢谢。

**Comment by huashengdun** [comment]
@sky800719 
已经加了, 示例如下
`http://localhost:8888/?command=ls -l`

**Comment by PhoenixPeca** [comment]
> Cross-domain links are supported, as long as the server has this `origin`. 
> A cross-domain domain name URL is sent when the server starts.
> 
> ```shell
> wssh --origin='http://www.example.com'
> ```
> 
> Browser-side code example,
> 
> ```js
> var target_window = window.open('https://webssh.domain.com');
> target_window.postMessage('hostname|port|username|password', '*');
> // target_window.postMessage(JSON.stringify(['hostname', 'port', 'username', 'password']), '*');
> ```

Hi I have tried this.. It doesnt seem to work.. :(

**Comment by PhoenixPeca** [comment]
How can I pass the parameters from another page to webssh without exposing the credentials to the URL? :(

**Comment by PhoenixPeca** [comment]
I tried to call the webssh api directly from another page to get the SSH websocket id as in:
````
{status: null, id: "139931239474768", encoding: "UTF-8"}
````

But I don't know how to pass it back to webssh to open an ssh window by just using the ID..

:(

**Comment by PhoenixPeca** [comment]
@huashengdun can you help me with this please?

**Comment by huashengdun** [comment]
> > Cross-domain links are supported, as long as the server has this `origin`.
> > A cross-domain domain name URL is sent when the server starts.
> > ```shell
> > wssh --origin='http://www.example.com'
> > ```
> > 
> > 
> > Browser-side code example,
> > ```js
> > var target_window = window.open('https://webssh.domain.com');
> > target_window.postMessage('hostname|port|username|password', '*');
> > // target_window.postMessage(JSON.stringify(['hostname', 'port', 'username', 'password']), '*');
> > ```
> 
> Hi I have tried this.. It doesnt seem to work.. :(
var target_window = window.open('https://webssh.domain.com');
// wait for the page fully loaded, then execute the line below
target_window.postMessage('hostname|port|username|password', '*');
