### ISSUE TITLE
Successfully installed but command not found

### ISSUE THREAD

**Issue by ReinforceZwei** [huashengdun/webssh#49]
I use `pip install webssh` and successfully installed the app.
But when I try to launch it with `wssh`, it said `-bash: wssh: command not found`
I am running Debian 9 on Raspberry Pi
Using Python 2.7.13
Here are the installation logs:
`Collecting webssh
  Using cached https://www.piwheels.org/simple/webssh/webssh-0.9.0-py2.py3-none-any.whl
Collecting tornado>=4.5.0 (from webssh)
Collecting paramiko>=2.3.1 (from webssh)
  Using cached https://files.pythonhosted.org/packages/cf/ae/94e70d49044ccc234bfdba20114fa947d7ba6eb68a2e452d89b920e62227/paramiko-2.4.2-py2.py3-none-any.whl
Collecting singledispatch (from tornado>=4.5.0->webssh)
  Using cached https://files.pythonhosted.org/packages/c5/10/369f50bcd4621b263927b0a1519987a04383d4a98fb10438042ad410cf88/singledispatch-3.4.0.3-py2.py3-none-any.whl
Collecting futures (from tornado>=4.5.0->webssh)
  Using cached https://files.pythonhosted.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl
Collecting backports-abc>=0.4 (from tornado>=4.5.0->webssh)
  Using cached https://files.pythonhosted.org/packages/7d/56/6f3ac1b816d0cd8994e83d0c4e55bc64567532f7dc543378bd87f81cebc7/backports_abc-0.5-py2.py3-none-any.whl
Collecting pynacl>=1.0.1 (from paramiko>=2.3.1->webssh)
  Using cached https://files.pythonhosted.org/packages/61/ab/2ac6dea8489fa713e2b4c6c5b549cc962dd4a842b5998d9e80cf8440b7cd/PyNaCl-1.3.0.tar.gz
Collecting cryptography>=1.5 (from paramiko>=2.3.1->webssh)
  Using cached https://files.pythonhosted.org/packages/69/ed/5e97b7f54237a9e4e6291b6e52173372b7fa45ca730d36ea90b790c0059a/cryptography-2.5.tar.gz
Collecting bcrypt>=3.1.3 (from paramiko>=2.3.1->webssh)
  Using cached https://files.pythonhosted.org/packages/ce/3a/3d540b9f5ee8d92ce757eebacf167b9deedb8e30aedec69a2a072b2399bb/bcrypt-3.1.6.tar.gz
Collecting pyasn1>=0.1.7 (from paramiko>=2.3.1->webssh)
  Using cached https://files.pythonhosted.org/packages/7b/7c/c9386b82a25115cccf1903441bba3cbadcfae7b678a20167347fa8ded34c/pyasn1-0.4.5-py2.py3-none-any.whl
Collecting six (from singledispatch->tornado>=4.5.0->webssh)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting cffi>=1.4.1 (from pynacl>=1.0.1->paramiko>=2.3.1->webssh)
  Using cached https://files.pythonhosted.org/packages/e7/a7/4cd50e57cc6f436f1cc3a7e8fa700ff9b8b4d471620629074913e3735fb2/cffi-1.11.5.tar.gz
Collecting asn1crypto>=0.21.0 (from cryptography>=1.5->paramiko>=2.3.1->webssh)
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting enum34 (from cryptography>=1.5->paramiko>=2.3.1->webssh)
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting ipaddress (from cryptography>=1.5->paramiko>=2.3.1->webssh)
  Using cached https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.4.1->pynacl>=1.0.1->paramiko>=2.3.1->webssh)
  Using cached https://www.piwheels.org/simple/pycparser/pycparser-2.19-py2.py3-none-any.whl
Building wheels for collected packages: pynacl, cryptography, bcrypt, cffi
  Running setup.py bdist_wheel for pynacl ... done
  Stored in directory: /home/pi/.cache/pip/wheels/c1/10/e7/66597ff71adf8cb7403527243c4b57c66a0d1dfdd8adf2eae4
  Running setup.py bdist_wheel for cryptography ... done
  Stored in directory: /home/pi/.cache/pip/wheels/26/7e/a3/34cb4fe18a871618b1f0f957fe17e7fd30cd1092c6e657a077
  Running setup.py bdist_wheel for bcrypt ... done
  Stored in directory: /home/pi/.cache/pip/wheels/6c/f0/60/8a8ebee44d14d3d6696f1e78960500777cb5b579caf33c1fe3
  Running setup.py bdist_wheel for cffi ... done
  Stored in directory: /home/pi/.cache/pip/wheels/e6/9e/cd/9f0b900a715af094d5a08cc50230728c08ef745ffb195c67e8
Successfully built pynacl cryptography bcrypt cffi
Installing collected packages: six, singledispatch, futures, backports-abc, tornado, pycparser, cffi, pynacl, asn1crypto, enum34, ipaddress, cryptography, bcrypt, pyasn1, paramiko, webssh
Successfully installed asn1crypto-0.24.0 backports-abc-0.5 bcrypt-3.1.6 cffi-1.11.5 cryptography-2.5 enum34-1.1.6 futures-3.2.0 ipaddress-1.0.22 paramiko-2.4.2 pyasn1-0.4.5 pycparser-2.19 pynacl-1.3.0 singledispatch-3.4.0.3 six-1.12.0 tornado-5.1.1 webssh-0.9.0`

**Comment by huashengdun** [comment]
Debian has more strict rules for granting permissions.
Do you install webssh using virtualenv?
If not, try to install it within a virtualenv.

**Comment by ReinforceZwei** [comment]
@larryathey installing `wssh` didn't solve my problem.
@huashengdun I can use `wssh` command now after installed `webssh` inside a virtual env. Thank you very much!
