### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by aixocm** [huashengdun/webssh#5]
I'm trying to add log audit features to this project. For example, I can log the operation commands of the end user and the screen recording function, but it has not been developed so far. Can you help us add these two functions to this project? thank you very much!

**Comment by huashengdun** [comment]
You can enable debug mode if you want to log the operation commands.

**Comment by aixocm** [comment]
I know, but that log content is accepted through the websocket protocol, so the format of the log content is a line per character, and is generated in real time, is there any way to judge I recorded the terminal after the Enter key is pressed My content

**Comment by huashengdun** [comment]
I guess you may need to check the data every time on reading,  '\r\n' is the enter key.
