### ISSUE TITLE
Utilization of a token server

### ISSUE THREAD

**Issue by nemeeks** [huashengdun/webssh#50]
@huashengdun 

I'm curious if I can implement this in a way that will allow the use of a "token server" for handling authentication. I'm looking to have a web server that a user is authenticated against make the initial call to wssh to get the id for the connection. This information is then passed to the user's connection to establish the actual SSH session with the endpoint. Right now we can get this to work by setting the origin policy to primary and by having an inbound NAT mask all traffic to the wssh server as coming from the same IP. If we disable inbound NAT and allow the true client IP to pass to the wssh server, we can't connect.

- If we do this in primary origin mode, we get a 403 on the GET call that passes the id to the server from the client connection. 

- If we do this with debug mode enabled and a wildcard in the origin, we get a websockets authentication error on the client connetion.

Can this be circumvented through the origin policy settings?

**Comment by huashengdun** [comment]
Right now this app doesn't have any authentication functionality implemented.
And you should not use `origin` policy as an authentication method. 
Maybe you can try option `tdstream` or option `policy`.

**Comment by huashengdun** [comment]
@nemeeks,
Check out this page, https://www.tornadoweb.org/en/stable/auth.html.
It may help you.

**Comment by litongjava** [comment]
[W 190227 18:01:55 handler:119] Public plain http request is forbidden.
[W 190227 18:01:55 web:2162] 403 GET / (59.41.206.231) 0.82ms
安装完成启动webssh使用浏览器访问遇到上面的错误,浏览器上显示403

**Comment by huashengdun** [comment]
@litongjava 
```bash
wssh --fbidhttp=False
```
