### ISSUE TITLE
pip安装成功但是登陆报错，环境是python3.6的虚拟环境中

### ISSUE THREAD

**Issue by xueshaobo1** [huashengdun/webssh#53]
(py3) [root@localhost webssh]# wssh
[I 190312 13:58:26 settings:98] WarningPolicy
[I 190312 13:58:26 main:39] Listening on 0.0.0.0:8888 (http)
[I 190312 13:58:28 web:2246] 200 GET / (192.168.0.105) 2.94ms
[W 190312 13:58:28 web:2246] 404 GET /static/css/bootstrap.min.css.map (192.168.0.105) 1.28ms
[W 190312 13:58:28 web:2246] 404 GET /static/css/fullscreen.min.css.map (192.168.0.105) 2.34ms
[W 190312 13:58:28 web:2246] 404 GET /static/js/popper.min.js.map (192.168.0.105) 2.21ms
[W 190312 13:58:28 web:2246] 404 GET /static/css/xterm.min.css.map (192.168.0.105) 2.30ms
[W 190312 13:58:28 web:2246] 404 GET /static/js/bootstrap.min.js.map (192.168.0.105) 1.09ms
[I 190312 13:58:28 web:2246] 200 GET /static/img/favicon.png (192.168.0.105) 1.28ms
[I 190312 13:58:32 handler:313] Connecting to 192.168.0.190:22
[I 190312 13:58:32 transport:1746] Connected (version 2.0, client OpenSSH_6.6.1)
/opt/py3/lib64/python3.6/site-packages/paramiko/kex_ecdh_nist.py:39: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  m.add_string(self.Q_C.public_numbers().encode_point())
/opt/py3/lib64/python3.6/site-packages/paramiko/kex_ecdh_nist.py:96: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
  self.curve, Q_S_bytes
/opt/py3/lib64/python3.6/site-packages/paramiko/kex_ecdh_nist.py:111: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  hm.add_string(self.Q_C.public_numbers().encode_point())
/opt/py3/lib64/python3.6/site-packages/paramiko/client.py:822: UserWarning: Unknown ssh-ed25519 host key for 192.168.0.190: b'ac404accca871e5e0a69aed7b86f2f58'
  key.get_name(), hostname, hexlify(key.get_fingerprint())
[I 190312 13:58:32 transport:1746] Authentication (password) successful!
[I 190312 13:58:32 web:2246] 200 POST / (192.168.0.105) 214.33ms
[I 190312 13:58:32 web:2246] 101 GET /ws?id=140052932837504 (192.168.0.105) 1.72ms
[I 190312 13:58:32 handler:393] Connected from 192.168.0.105:60283
[E 190312 13:58:32 web:1788] Uncaught exception GET /ws?id=140052932837504 (192.168.0.105)
    HTTPServerRequest(protocol='http', host='192.168.0.180:8888', method='GET', uri='/ws?id=140052932837504', version='HTTP/1.1', remote_ip='192.168.0.105')
    Traceback (most recent call last):
      File "/opt/py3/lib64/python3.6/site-packages/tornado/websocket.py", line 952, in _accept_connection
        open_result = handler.open(*handler.open_args, **handler.open_kwargs)
      File "/opt/py3/lib64/python3.6/site-packages/webssh/handler.py", line 408, in open
        self.set_nodelay(True)
      File "/opt/py3/lib64/python3.6/site-packages/tornado/websocket.py", line 561, in set_nodelay
        assert self.stream is not None
    AssertionError
[W 190312 13:58:35 worker:16] Recycling worker 140052932837504
[I 190312 13:58:35 worker:99] Closing worker 140052932837504 with reason: worker recycled
[I 190312 13:58:35 worker:106] Connection to 192.168.0.190:22 lost

**Comment by huashengdun** [comment]
你安装的tornado是不是6版本的？
tornado 6 代码改了很多，这个程序不支持。
你可以安装 tornado 5.1.1.

**Comment by huashengdun** [comment]
tornado 6 要求python 3.5.2或更新。
我暂时不打算更新代码了。
如果非要用tornado 6， 解决办法就是 注解 handler.py 408 行，
```python
# self.set_nodelay(True)
```

**Comment by huashengdun** [comment]
代码更新了，现在支持 tornado 6 了。

**Comment by huashengdun** [comment]
https://github.com/tornadoweb/tornado/pull/2613/commits/4677c54cc18bbfbdf0f4dadf11610fab6203fd63
这个是tornado 6的一个bug， 本来应该等tornado发布新版本。

**Comment by xueshaobo1** [comment]
非常感谢，问题解决了。我安装的tornado确实是6.0.1的版本
