### ISSUE TITLE
页面403

### ISSUE THREAD

**Issue by cai823294620** [huashengdun/webssh#54]
使用Nginx做的反代，打开页面却是403:Forbidden.

**Comment by huashengdun** [comment]
把反代的Nginx配置贴出来看看。

**Comment by cai823294620** [comment]
sorry，我是adminset运维管理平台里封装的webssh，然后做的端口映射，用127.0.0.1:8888进行访问的，其实并没有使用Nginx。

**Comment by huashengdun** [comment]
从上面报的错误来看，是由“/usr/local/lib/python2.7/dist-packages/tornado/web.py”的205行，SyntaxError 造成的。

**Comment by cai823294620** [comment]
@huashengdun 现在更改为Centos7的版本后一切正常。谢谢

**Comment by huashengdun** [comment]
不客气。
