### ISSUE TITLE
I need some help with terminal encodings

### ISSUE THREAD

**Issue by pedrogrolla** [huashengdun/webssh#55]
I'm trying to set a new terminal session with other encode than the default encode, how can i set this option? There is any configuration file or a way to set parameters on wssh?

**Comment by huashengdun** [comment]
Enter your browser console, then run `wssh.reset_encoding();`.

**Comment by huashengdun** [comment]
Enter your browser console, then run `wssh.set_encoding(encoding);`.

**Comment by huashengdun** [comment]
Passing an ecoding
`http://localhost:8888/#encoding=utf-8`
