### ISSUE TITLE
Type of certificate

### ISSUE THREAD

**Issue by lenbobopp** [huashengdun/webssh#56]
While I apply the certificate with the type of RSA, the python shows this Error information below:
` File "/usr/lib/python2.7/site-packages/webssh/settings.py", line 116, in get_ssl_context
    ssl_ctx.load_cert_chain( options.certfile,options.keyfile)
ssl.SSLError: [SSL] PEM lib (_ssl.c:2574)
`
But it can apply the ECDSA certificate and performs well.

**Comment by huashengdun** [comment]
I'v just tested with RSA certificate and it works.


```bash
openssl req -newkey rsa:2048 -nodes -keyout ssl.key -x509 -days 1095 -out ssl.crt
```
```bash
wssh --certfile='ssl.crt' --keyfile='ssl.key'
```
