### ISSUE TITLE
top命令在xterm显示不正常

### ISSUE THREAD

**Issue by zhxiaohe** [huashengdun/webssh#57]
您好,我现在遇到一个Linux top命令的问题
如图,我执行top命令 一开始是固定
![116281554779502_ pic](https://user-images.githubusercontent.com/11907113/55771910-839d8200-5abc-11e9-8216-9c68eb2523df.jpg)
然后过一会儿或者进程比较多xterm样式就飞了
![image](https://user-images.githubusercontent.com/11907113/55771941-aa5bb880-5abc-11e9-81f7-b5732337124f.png)
请问这种情况有解决办法吗？

**Comment by huashengdun** [comment]
执行`top`命令前刷新下屏幕`Ctrl+L`会不会好点？

**Comment by zhxiaohe** [comment]
跟ctrl+l没关系哈,感觉跟chan.recv(BUF_SIZE)取到的值有关,我在研究看看,感谢答复☺️

**Comment by huashengdun** [comment]
top命令差不错每隔3秒实时刷新。
浏览器大小改变也会实时地改变channel_pty大小。
top命令跟channel_pty也有关系。
所以在执行top命令时，最好不要改变浏览器大小。

**Comment by zhxiaohe** [comment]
木有啊,我就是打开浏览器执行top命令,其他什么都没动,今天还没来得及处理这问题,等我搞定了给您个反馈O(∩_∩)O谢谢up主

**Comment by huashengdun** [comment]
@zhxiaohe 
xterm.js更新到了 3.12.2，我这边好像没有这个问题了。
你那边还存在这个问题吗？

**Comment by zhxiaohe** [comment]
我还没升级,等我升级下看看哈

**Comment by huashengdun** [comment]
我这边测试下来似乎没这个问题了，可能跟xterm.js版本有关系。
先关闭这个issue。

**Comment by zhxiaohe** [comment]
好的,辛苦up主
