### ISSUE TITLE
Worker recycled when connecting

### ISSUE THREAD

**Issue by TomEscolano** [huashengdun/webssh#59]
Hello,
I just ran a docker instance of webssh.
But when I try to connect to my host, the authentication is successfull but the worker is beign recylced instantly.
Any idea ?

> web_1  | [I 190419 14:12:40 web:2246] 200 GET / (172.19.0.1) 2.64ms
web_1  | [I 190419 14:12:41 web:2246] 304 GET /static/css/bootstrap.min.css (172.19.0.1) 5.19ms
web_1  | [I 190419 14:12:41 web:2246] 304 GET /static/css/xterm.min.css (172.19.0.1) 9.19ms
web_1  | [I 190419 14:12:41 web:2246] 304 GET /static/css/fullscreen.min.css (172.19.0.1) 11.34ms
web_1  | [I 190419 14:12:41 web:2246] 304 GET /static/js/jquery.min.js (172.19.0.1) 12.82ms
web_1  | [I 190419 14:12:41 web:2246] 304 GET /static/js/popper.min.js (172.19.0.1) 14.09ms
web_1  | [I 190419 14:12:41 web:2246] 304 GET /static/js/xterm.min.js (172.19.0.1) 0.72ms
web_1  | [I 190419 14:12:41 web:2246] 304 GET /static/js/main.js (172.19.0.1) 0.95ms
web_1  | [I 190419 14:12:41 web:2246] 304 GET /static/js/bootstrap.min.js (172.19.0.1) 2.53ms
web_1  | [I 190419 14:12:41 web:2246] 304 GET /static/js/fullscreen.min.js (172.19.0.1) 1.88ms
web_1  | [I 190419 14:12:45 handler:313] Connecting to my.host:22
web_1  | [I 190419 14:12:45 transport:1746] Connected (version 2.0, client OpenSSH_7.4p1)
web_1  | [I 190419 14:12:45 transport:1746] Authentication (password) successful!
web_1  | [I 190419 14:12:45 web:2246] 200 POST / (172.19.0.1) 180.05ms
web_1  | [W 190419 14:12:48 worker:16] Recycling worker 139873205021160
web_1  | [I 190419 14:12:48 worker:99] Closing worker 139873205021160 with reason: worker recycled
web_1  | [I 190419 14:12:48 worker:106] Connection to my.host:22 lost

**Comment by huashengdun** [comment]
Hi TomEscolano,

Normally the log looks like this,
![Screenshot from 2019-04-20 06-41-45](https://user-images.githubusercontent.com/909962/56447087-eef71780-6338-11e9-9eab-a8c20309d068.png)
You see there is a `GET` request issued immediately after the `POST` request.

Do you use a browser?
If you do, check if there is any error message in your browser console.

**Comment by TomEscolano** [comment]
Hi,

Yes, I use a browser (Latest version of Firefox).
I just checked my console and there is an error in Jquery.min.js
![image](https://user-images.githubusercontent.com/15269866/56794525-9cbd6700-680e-11e9-9c5b-0c8aa637c151.png)
I can't get my hands on this error...

**Comment by huashengdun** [comment]
Hi,

Can you tell me the whole url by which you access to the webssh page?

**Comment by TomEscolano** [comment]
I access the webssh page via the following URL:
> http://10.4.119.28:8888/#port=22&host=localhost

I've added a little JS script to the page to prefill the inputs of the form with URL given parameters

**Comment by huashengdun** [comment]
Yes, the syntax error was caused by your URL.
main.js currently can't handle this kind of url format.

**Comment by huashengdun** [comment]
Hi TomEscolano,
Maybe you can pass values in this way:
> http://10.4.119.28:8888/?port=22&host=localhost

**Comment by huashengdun** [comment]
Fixed https://github.com/huashengdun/webssh/commit/d69d8cfa7a4d15fb081aede9e2b3e49a21fb8435

**Comment by huashengdun** [comment]
Hi TomEscolano,
I have updated main.js, now it supports passing arguments by url like:
`http://localhost:8888/#hostname=xx&username=yy`
`http://localhost:8888/?hostname=xx&username=yy`
