### ISSUE TITLE
能在url中获取ip地址，服务器查询改ip对应的账号密码连接的方式吗？

### ISSUE THREAD

**Issue by zhaowangda** [huashengdun/webssh#6]

**Comment by zhaowangda** [comment]
etcd中保存有每一台服务器的账号密码，只要在get中回去ip或id就可以了，服务器会自动查找对应的账号和密码返回连接终端

**Comment by zhaowangda** [comment]
你知道怎么在django 中开发这个功能吗？

**Comment by huashengdun** [comment]
This app does not save any information(except logging), so it does not have the functionality you asked.
And welcome to contribute to this app if you need some functionalities it does not have right now.
