### ISSUE TITLE
浏览器缩放时偶尔出bug

### ISSUE THREAD

**Issue by leavest** [huashengdun/webssh#60]
![image](https://user-images.githubusercontent.com/30454841/57186828-6ec7d900-6f18-11e9-8d75-e77392f14677.png)
在测试缩放时，浏览器变这样，敲键盘输入光标会移动，不显示东西。
不是每次缩放都这样，多缩放几次最终都变这样

**Comment by huashengdun** [comment]
使用的是什么浏览器？
浏览器console有什么错误提示吗？

**Comment by leavest** [comment]
谷歌浏览器
错误提示
```
Uncaught TypeError: Cannot read property 'get' of undefined
    at e._forEachCell (xterm.min.js:1)
    at e._drawBackground (xterm.min.js:1)
    at e.onGridChanged (xterm.min.js:1)
    at xterm.min.js:1
    at Array.forEach (<anonymous>)
    at e._renderRows (xterm.min.js:1)
    at e._innerRefresh (xterm.min.js:1)
    at xterm.min.js:1
```

**Comment by huashengdun** [comment]
你使用的谷歌浏览器是什么版本？
其它浏览器也有这样的问题吗？

**Comment by leavest** [comment]
> 你使用的谷歌浏览器是什么版本？
> 其它浏览器也有这样的问题吗？

版本73.0.3683.103
火狐也有这个问题

**Comment by huashengdun** [comment]
https://github.com/xtermjs/xterm.js/issues/1926
可能是xterm.js 3.11.0的一个bug。
不过，我使用firefox和chrome下倒还没有出现这个问题。

**Comment by leavest** [comment]
来回切换测试几次
用最新的xterm.js，似乎没有问题了
用项目当前的xterm.js确实有问题

**Comment by huashengdun** [comment]
> 来回切换测试几次
> 用最新的xterm.js，似乎没有问题了
> 用项目当前的xterm.js确实有问题

感谢测试并反馈。
