### ISSUE TITLE
Change xterm colors?

### ISSUE THREAD

**Issue by nealdav** [huashengdun/webssh#61]
Thank you for your excellent work here. 
What is the recommended way to change the xterm colors or theme?

**Comment by huashengdun** [comment]
Haven't dive into that part of area.
Do you have some ideas or suggestions?

**Comment by huashengdun** [comment]
You are welcome.
I haven't thought that functionality before.
But any ideas or suggestions are welcome.

**Comment by nealdav** [comment]
👍🏽I’ll take a look

**Comment by huashengdun** [comment]
Here is a comment on an issue of how to set background color on terminal which may help you.
https://github.com/xtermjs/xterm.js/issues/1719#issuecomment-426344864

**Comment by huashengdun** [comment]
Just added a method `set_bgcolor` to `wssh`.
Run following command in your browser console to change the terminal background color to green.
```js
wssh.set_bgcolor('green')
```

**Comment by huashengdun** [comment]
Also now it supports passing a terminal background color by url like:
`http://localhost:8888/?bgcolor=green`
`http://localhost:8888/#bgcolor=green`

**Comment by nealdav** [comment]
I'm finally circling back to this - Thank you for adding this feature @huashengdun !

**Comment by huashengdun** [comment]
> I'm finally circling back to this - Thank you for adding this feature @huashengdun !

You are welcome.
