### ISSUE TITLE
websocket连接经常断

### ISSUE THREAD

**Issue by llkllk** [huashengdun/webssh#62]
websocket连接经常断，毫无规律，与nginx timeout都没什么关系，每次重新登录都得从头开始，这是致命伤。

**Comment by huashengdun** [comment]
你使用的是什么浏览器？
websocket断开，浏览器或者服务端有没有什么日志提示？
或许你可以参考下这个 https://github.com/huashengdun/webssh/issues/18

**Comment by llkllk** [comment]
网络环境造成的，局域网没问题，gateone对这个问题处理得较好，只是刷新后行宽有问题。

**Comment by huashengdun** [comment]
网络环境差的话，可以启用 websocket ping 机制, 可以把Websocket ping interval设置小点，比如20秒。
```bash
wssh --wpintvl=20
```
