### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by SilhouetteKnight** [huashengdun/webssh#63]
I little help please

I installed it using virtual environment

![pp1](https://user-images.githubusercontent.com/50826568/58011708-6f21c000-7b25-11e9-93d1-1f98581bbc3f.jpg)

**Comment by huashengdun** [comment]
Public plain http request is forbidden by default.
```bash
wssh --fbidhttp=False
```

**Comment by SilhouetteKnight** [comment]
Hello, this works properly, had to add letsencrypt crt and keys, works fine.

Thank you for this!

**Comment by huashengdun** [comment]
Cool, close this issue.

**Comment by lustime** [comment]
> ```shell
> ```shell
> wssh --fbidhttp=False
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
> 大哥 。    如果是使用docker-compose启动    这个配置需要加在什么位置
> ```

同问

**Comment by royzhao7** [comment]
> > ```shell
> > ```shell
> > wssh --fbidhttp=False
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 大哥 。    如果是使用docker-compose启动    这个配置需要加在什么位置
> 
> 同问
![image](https://github.com/user-attachments/assets/3ceefdcb-d1b7-45ba-b62a-e7fc2cf41571)
修改settings.py 35行  default值改为False
