### ISSUE TITLE
如何移除xsrf

### ISSUE THREAD

**Issue by chenshun00** [huashengdun/webssh#64]
我们现在想将webssh集合到内部发布系统，减少登录堡垒机到操作，请问下如何将xsrf移除呢

目前已经采取过到是，请求 `127.0.0.1:8888` 抓取 _xsrf，发送`post`请求获取websokcet链接的`id`,然后使用该ID进行链接，但是auth没有通过

**Comment by huashengdun** [comment]
启动服务时加个参数`xsrf`试试。
```bash
wssh --xsrf=False
```

**Comment by chenshun00** [comment]
@huashengdun  `Websocket authentication failed` 

![image](https://user-images.githubusercontent.com/26037282/58452029-685c0400-8148-11e9-8319-19016e62e3d1.png)

![image](https://user-images.githubusercontent.com/26037282/58452017-5da16f00-8148-11e9-8f1d-716dd8f93c82.png)

**Comment by chenshun00** [comment]
@huashengdun 我先了解下，有问题再提issue , 打扰了

**Comment by huashengdun** [comment]
好的。

**Comment by chenshun00** [comment]
@huashengdun 应该是找到问题了，我是通过 `java` 去获取的ID，`python` 那边根据这次`http`请求，和 `ssh服务器` 保持了一个tcp链接，当我http链接断开，对应的ssh服务器tcp链接也就断开了，而我的需求是通过我们的发布系统作为中转站，就出现了这个问题。

不知道有没有什么好的方法去规避呢？

**Comment by huashengdun** [comment]
ID获取后，还有下一步，使用这个ID与`wssh`服务器建立一个websocket连接。

**Comment by chenshun00** [comment]
嗯，我们在建立这一步花的时间比较长，到底tcp连接被kill了，目前的方法是通过一个中间商去转发到wssh，应该能解决问题，不是xsrf的问题，感谢
