### ISSUE TITLE
启动wssh无法通过浏览器访问，报错403

### ISSUE THREAD

**Issue by bjtulq** [huashengdun/webssh#65]
wssh的日志如下：
[I 190529 09:15:52 settings:98] WarningPolicy
[I 190529 09:15:52 main:39] Listening on 0.0.0.0:8022 (http)
[W 190529 09:16:09 handler:119] Public plain http request is forbidden.
[W 190529 09:16:09 web:2162] 403 GET / (61.148.244.179) 1.37ms
[W 190529 09:18:33 handler:119] Public plain http request is forbidden.
[W 190529 09:18:33 web:2162] 403 GET / (61.148.244.179) 0.70ms

浏览器里面报403
非常感谢

**Comment by huashengdun** [comment]
https://github.com/huashengdun/webssh/issues/63
