### ISSUE TITLE
How to import powerline font for oh-my-zsh?

### ISSUE THREAD

**Issue by demyxco** [huashengdun/webssh#68]
Hi, I'm building a dashboard to connect to my servers and all my servers have oh-my-zsh installed using the agnoster theme and it's causing webssh terminal to show empty squares. I've tried importing it via @font-face:

```
<style>
    @font-face { 
        font-family: 'Powerline'; src: url('../asset/powerline.ttf') format('truetype'); 
    }
</style>
```

Any help is appreciated! Thank you.

[![alt text](https://cloud.demyx.com/s/RdMe4nmfJF6nt8Z/preview "preview")](https://cloud.demyx.com/s/RdMe4nmfJF6nt8Z/preview)

**Comment by huashengdun** [comment]
Right now this app doesn't support changing of font family.
But the empty squares really was caused by your server and webssh terminal using the different font families?
Do your servers show text correctly when using the agnoster theme?

**Comment by demyxco** [comment]
It looks like using my laptop's terminal
![](https://cloud.demyx.com/s/7EP7TKYbXEXomyc/preview)

**Comment by huashengdun** [comment]
Seems the default font family used by the webssh terminal can't render the prompt line correctly.
Thus we need to support using custom font family.

**Comment by huashengdun** [comment]
Hi demyxco,

I have just updated my code.
Please update your code to my latest commit to test the custom font family stuff.
Also make sure your powerline font loaded successfully in your page with your url('../asset/powerline.ttf').
Please let me know if it works or not.

**Comment by demyxco** [comment]
Is your commit updated in the pip repo? If not, I can just manually git clone and replace the main.js.

**Comment by huashengdun** [comment]
Pip repo hasn't updated yet, only the Github repo updated.

**Comment by demyxco** [comment]
Awesome, it works now! I'm including your project into my Docker image.

![](https://cloud.demyx.com/s/QLEQ88rQPZR7aRP/preview)

**Comment by huashengdun** [comment]
I am glad to hear that.
Thanks for introducing this project to your Docker image.

**Comment by demyxco** [comment]
Hi, quick question; how do you change the font size of the terminal?

**Comment by huashengdun** [comment]
Not supported.
A simple way is to zoom in/out your browser.
