### ISSUE TITLE
SSH passphrase keeps saying wrong password

### ISSUE THREAD

**Issue by demyxco** [huashengdun/webssh#69]
I decided to make a test key with the command:
```
ssh-keygen -t RSA
```
Loaded the privatekey in the form, put the correct password, and then this error keeps popping up:
```
Wrong password u'test' for decrypting the private key.
```
I noticed the "u" in the error message, is that character being added on form submission?

**Comment by huashengdun** [comment]
If you are using Python 2,  the error message should be prefixed with character 'u'.
Make sure your passphrase is correct.

**Comment by huashengdun** [comment]
Make sure your passphrase is correct.
If you are using Python 2, the error message should be prefixed with the character 'u'.
The form only submits the characters you type.

**Comment by demyxco** [comment]
Why was this closed? I'm still getting the error for passphrase.

```
[I 190624 03:00:08 handler:224] Trying RSAKey
[I 190624 03:00:08 handler:224] Trying DSSKey
[I 190624 03:00:08 handler:224] Trying ECDSAKey
[I 190624 03:00:08 handler:224] Trying Ed25519Key
[W 190624 03:00:08 web:1667] 400 POST / (172.69.142.42): Wrong password u'test' for decrypting the private key.
```

The passphrase works because I can connect to the remote server using an actual terminal.

```
bash-5.0$ ssh demyx@xxx.xxx.xxx.xxx date
Enter passphrase for key '/home/demyx/.ssh/id_rsa': 
Mon Jun 24 03:05:59 PDT 2019
bash-5.0$ 
```

Is this a python version issue?

**Comment by huashengdun** [comment]
No, it is not a python version issue.
I have unit tests tested against different Python versions.

As for as I know you can not generate a rsa key with a passphrase of four characters. (minimum five characters)

**Comment by demyxco** [comment]
Same thing with a longer generated password

```
Wrong password u'1yUsVsjQH4r304' for decrypting the private key.
```

Any other setting I can check out?

**Comment by huashengdun** [comment]
I have just tested against a encrypted rsa key and it works as expected.
Did you use the correct key with the correct passphrase?
If you use a fake key with a random password, it also prompts you some thing like "Wrong password...".

**Comment by demyxco** [comment]
What command did you use to generate the RSA? I read somewhere that paramiko doesn’t use openssh library.

**Comment by huashengdun** [comment]
command like that
```bash
ssh-keygen -t rsa -b 2048 -f id_rsa
```

**Comment by demyxco** [comment]
Yeah it doesn't work still, I will stick with no password keys for now. Not sure why but I will close as I don't have time to debug it. Great job on the project by the way!

**Comment by demyxco** [comment]
Hi, me again. Seems like the app doesn't like my RSA key generations so I switched to ed25519 and now the passphrase works!

**Comment by huashengdun** [comment]
![tests](https://user-images.githubusercontent.com/909962/60084601-68145000-976a-11e9-9ab7-dc37f9f93fcc.png)

**Comment by huashengdun** [comment]
From the above image, you see I tested the dsa rsa ecdsa ed25519 keys generated by ssh-keygen and  they all work as expected.
So I am curious what tool did you use to generate the keys.

**Comment by demyxco** [comment]
I've been using this command 

```
ssh-keygen -t rsa
```

But passphrase doesn't work with your app. So now I'm using:

```
ssh-keygen -t ed25519
```

Which is supposedly better than RSA

**Comment by huashengdun** [comment]
Hi demyxco,
I have noticed that `paramiko`  doesn't support new key format.
Maybe it is related to your problem.
Here are the links:
https://github.com/paramiko/paramiko/issues/1313
https://github.com/huashengdun/webssh/issues/73

**Comment by demyxco** [comment]
Yeah I noticed that macOS doesn't generate the old RSA keys, that's why it didn't work for me. What finally worked was using this:

```
ssh-keygen -m PEM -t RSA
```
