### ISSUE TITLE
redhat system webssh input 'history' except Disconnected shell

### ISSUE THREAD

**Issue by Aaron-Ming** [huashengdun/webssh#7]
I use the redhat6.6 operating system, and when I enter the 'history' command at shell, the webssh closes the connection exceptions.
The log on the server side is 'Disconnected from 127.0.0.1:64875'
It seems normal to see if there is no support for certain commands.

**Comment by huashengdun** [comment]
Hi, thank you for using this app and reporting errors here.

What is your Python version?

1) Try to start this app by passing "--logging=debug"?
2) Connect to your server, then enter the 'history' command, see if you can reproduce the error.

Normall it should support all linux commands, even "Ctrl+D" command.

**Comment by 1032231418** [comment]
I want to embed it on my platform，How to allow cross station post to submit data？
