### ISSUE TITLE
websocket authentication failed via HTTPS

### ISSUE THREAD

**Issue by bestilyq** [huashengdun/webssh#71]
hi huashengdun,
我的webssh在vps上运行起来了，只启用http方式没有问题，但是HTTPS就会报Websocket authentication failed.错误，我的配置有什么问题吗？
wssh --port=8080 --sslport=8443 --certfile='cert.crt' --keyfile='cert.key' --xheaders=False --policy=autoadd --log-file-prefix=/var/log/webssh.log
我的域名通过cloudflare解析并开启了CDN。

**Comment by huashengdun** [comment]
可能是开启CDN后导致Websocket authentication failed.
关闭CDN看看什么效果。

**Comment by huashengdun** [comment]
由于你启用了cloudflare CDN，所以你的域名每次被解析出来的IP地址可能不同。
同时你服务器禁用xheaders功能，所以wssh是以直接请求的cloudflare机子作为客户，所以wssh认为两次请求来源于不同客户（IP不同），所以就会导致以上websocket认证错误。

所以使用http或者https访问一样的， 不管使用什么协议，两次请求dns解析你域名是同一个IP地址就没有问题，不同ip地址就会导致该错误。

解决方法：

1. wssh服务作为独服并启用xheaders功能(cloudfare支持X-Forwarded-For header)，访问形式如下：

  ```
  client <---> cloudflare <---> wssh
  ```

2. wssh服务禁用xheaders功能，并使用nginx作为前置代理，访问形式如下：
  ```
  client <---> cloudflare <---> nginx <---> wssh
  ```

**Comment by huashengdun** [comment]
我代码更新了。
解决方法稍微有点变化。

1. wssh服务启用`xheaders`功能和`xffirst`选项，可行的访问方式：
```
client <---> cloudflare <---> wssh
```
```
client <---> cloudflare <---> nginx <---> wssh   # ngin需配置X-Forwarded-For
```
2. wssh服务启用`xheaders`功能和不启用`xffirst`选项，可行的访问方式：
```
client <---> cloudflare <---> wssh
```
3. wssh服务禁用xheaders功能，并使用nginx作为前置代理，可行的访问形式：
```
client <---> cloudflare <---> nginx <---> wssh   # ngin无需配置X-Forwarded-For
```

**Comment by bestilyq** [comment]
可以了，问题已解决👍
