### ISSUE TITLE
登录报错

### ISSUE THREAD

**Issue by nmgmax** [huashengdun/webssh#72]
您好,登录报错.
![2019-07-09_181604](https://user-images.githubusercontent.com/52702943/60884716-34fcb100-a280-11e9-8dda-4706fd8415ff.png)

部署环境:同一网络中,一台服务器安装Nginx做代理,另一台服务器上部署webssh.

在不使用Nginx做代理的情况下,可以正常使用.

**Comment by huashengdun** [comment]
这个报错跟如何部署关系不大，只要部署的时候不去刻意改变origin这些header.
