### ISSUE TITLE
Is there a good way to manage private keys?

### ISSUE THREAD

**Issue by ghostbody** [huashengdun/webssh#77]
webssh is excellent to meet our requirements. However, our machines use RSA key pairs for authentication in which we need to select the private key to login onto the machine through webssh each time.

Is there a better way to do this? I have several ideas:

1. Set a default file path value for the file uploader. This is impossible due to browser security limits.
2. Set up a "private keys management system" or "ssh-agent" somewhere. But it's dangerous to store users private keys no matter where I save it, on a server or store it in the web storage (localStorage or IndexDb)

Do you have any good idea? Thanks so much!

**Comment by huashengdun** [comment]
I don't think storing users's private keys in somewhere is a good idea.
Since they are private keys it is OK to just let users keep their private keys.
They will take the responsibility for keeping and managing their private keys.
