### ISSUE TITLE
Recycle worker问题

### ISSUE THREAD

**Issue by Byshx** [huashengdun/webssh#79]
将webssh部署到nginx后，通过端口8080转发到指定端口，启动会提示recycle worker，然后丢失连接，但直接部署到端口8080就不会有这个问题？

**Comment by huashengdun** [comment]
把你的nginx配置贴出来看一下。

**Comment by Byshx** [comment]
user root;
worker_processes auto;
pid /run/nginx.pid;

events {
	worker_connections 768;
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	# server_tokens off;

	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;
	gzip_disable "msie6";

	# gzip_vary on;
	# gzip_proxied any;
	# gzip_comp_level 6;
	# gzip_buffers 16 8k;
	# gzip_http_version 1.1;
	# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# Virtual Host Configs
	##

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;

	upstream system{
		server localhost:6060;	
	}		
	upstream wssh{
		server localhost:6666;
	}	
	server
	{
		listen 8080;
		server_name localhost;
		location /{
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
			proxy_set_header Host &http_host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Real-PORT $remote_port;
			proxy_http_version 1.1;
			proxy_read_timeout 300;
			#transmit to wssh
			proxy_pass http://wssh;
		}
		location ^~/System{
			proxy_set_header Host $host;
			proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
			#transmit to System
			proxy_pass http://system;
		}
	}
}


#mail {
#	# See sample authentication script at:
#	# http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
# 
#	# auth_http localhost/auth.php;
#	# pop3_capabilities "TOP" "USER";
#	# imap_capabilities "IMAP4rev1" "UIDPLUS";
# 
#	server {
#		listen     localhost:110;
#		protocol   pop3;
#		proxy      on;
#	}
# 
#	server {
#		listen     localhost:143;
#		protocol   imap;
#		proxy      on;
#	}
#}

**Comment by huashengdun** [comment]
这行配置好像有问题，```proxy_set_header Host &http_host;``` 应该是
```proxy_set_header Host $http_host;```

**Comment by Byshx** [comment]
感谢！

**Comment by Byshx** [comment]
另外，如何修改可以让webssh从 localhost:8080/ 改到 localhost:8080/WebSSH   ?

**Comment by huashengdun** [comment]
https://github.com/huashengdun/webssh/issues/16
