### ISSUE TITLE
Outdated xterm.js and other dependencies

### ISSUE THREAD

**Issue by xnoreq** [huashengdun/webssh#85]
It looks like you're using xterm.js v3.12.2 but the current version is v4.0.1.

Also, I'm not sure why any of the other libraries are needed in modern browsers.

**Comment by huashengdun** [comment]
Yes, the version of xterm.js which `webssh` is using is 3.12.
The fullscreen functionality needs `fullscreen.min.js` .

**Comment by xnoreq** [comment]
Can you update xterm js?

>

**Comment by huashengdun** [comment]
Does xtermjs v4.0.1 have some outstanding features?

**Comment by xnoreq** [comment]
It has some features but the plethora of bugs (that range from incorrect rendering to data loss) that were fixed are way more important.

**Comment by treydempsey** [comment]
I've created a PR with a patch to upgrade to xtermjs 4.2.0. See it here: https://github.com/huashengdun/webssh/pull/104

**Comment by huashengdun** [comment]
Merged the PR from treydempsey, xterm.js upgraded to v4.2.0.
