### ISSUE TITLE
Websocket authentication failed.

### ISSUE THREAD

**Issue by iyangyuan** [huashengdun/webssh#87]
作者你好，请教一个问题。
我尝试使用一台公共的机器去调用/接口去获取ws的连接id，然后在其他机器上使用这个id创建连接，这样可以避免密码暴漏在前端，尝试之后服务端报错：Websocket authentication failed.
我不懂Python，大概看了下，是有IP限制吗？如何解除这种限制呢？
谢谢

**Comment by huashengdun** [comment]
对，就是这么设计的，ID是和IP绑定在一起的。
你说的“避免密码暴漏在前端”中的密码是这个ID吧。
这个不存在的，ID使用是一次性的（而且还有时效），一旦使用后就会失效。
修改的话，你从worker.py中定义的clients入手。

**Comment by iyangyuan** [comment]
如果不绑定就好了。。。
我说的密码是ssh的密码，按照现在的设计，我必须把ssh的账号密码传给前端，从前端登陆，如果id不绑定ip，我就可以统一分发id，而不是分发账号密码。
实际的需求是有上百台机器需要管理。

**Comment by iyangyuan** [comment]
感谢您的解答

**Comment by huashengdun** [comment]
把申请ID的机子和使用ID的机子组建一个网，使用同一个网关就行了。
或者使用同一个代理也行。
