### ISSUE TITLE
Can I add a subpath?

### ISSUE THREAD

**Issue by vickllny** [huashengdun/webssh#88]
Can I add a subpath?
I want to add a subpath like /webssh and then reverse proxy through nginx, but I visited http://192.168.1.100/webssh and the all static resources reported 404, below is my nginx configuration.        
location /webssh {
                proxy_pass         http://192.168.91.111:8888/;
                proxy_set_header  Host              $host:$server_port;
                proxy_set_header  X-real-IP         $remote_addr;
                proxy_set_header  X-forwarded-for   $proxy_add_x_forwarded_for;
                proxy_set_header  X-Forwarded-Proto  $scheme;
        }
All static resource url prefixes are not /webssh
what should I do?

**Comment by huashengdun** [comment]
```location /webssh/```

**Comment by vickllny** [comment]
It works. thx
