### ISSUE TITLE
Configure timeout?

### ISSUE THREAD

**Issue by macau23** [huashengdun/webssh#91]
If the ssh session is idle for a while (no screen updated) I get returned to the login form - is this configurable or can I disable it?

**Comment by huashengdun** [comment]
You can enable the ping/pong functionality on server side. For example
```
wssh --wpintvl=20
```
The server will close the tcp connection after idling for 60 seconds (3 * 20).

**Comment by huashengdun** [comment]
Browsers also have their connection timeouts,  take a look at this
https://fastmail.blog/2011/06/28/http-keep-alive-connection-timeouts/

**Comment by macau23** [comment]
Works great - thanks.

**Comment by Spearklea** [comment]
Dont works
