### ISSUE TITLE
RFE: Support a configurable path/use relative paths

### ISSUE THREAD

**Issue by macau23** [huashengdun/webssh#92]
I often have a reverse proxy https://proxy.example.com/appname/ which makes the app less discoverable, and allows use of a single ssl cert. I can't get this working with webssh, but other projects (like syncthing) work around this with relative paths to assets rather than absolute paths.

Maybe the paths could be configurable or relative to the assets (/ws/, etc.)

**Comment by huashengdun** [comment]
This may help you https://github.com/huashengdun/webssh/issues/88

**Comment by macau23** [comment]
I added a slash at the end of proxy_pass and the X-Forwarded* headers and now it works. Thank you.
