### ISSUE TITLE
Cross origin operation is now allowed.

### ISSUE THREAD

**Issue by bingart** [huashengdun/webssh#98]
deployed webssh behind nginx (windows), connect OK with PC browser.
While connect failed with safari in iphone.
report “Cross origin operation is now allowed.”
![webssh](https://user-images.githubusercontent.com/29355911/69020712-73ee0080-09f0-11ea-8a67-4ed3e8ab4887.jpg)

**Comment by bingart** [comment]
[W 191118 10:46:53 web:1667] 403 POST / (172.16.xx.xxx): Cross origin operation is not allowed.
[I 191118 10:46:53 web:2162] 200 POST / (172.16.xx.xxx) 3.85ms

server report above.

**Comment by bingart** [comment]
wssh --origin="*" --debug
to fix the error, while connection to ssh server always colsed by worker.

**Comment by huashengdun** [comment]
xtermjs doesn't support mobile.
https://github.com/xtermjs/xterm.js/issues/1902
